class StrikeExecutor_ApplyStatusEffect extends EffectExecutor_Scripted
{

	public function Process( ctx : EffectScriptContext, applierCtx : EffectExecutionScriptContext ) : Bool
	{
		var puppet : ScriptedPuppet;
		var data : EffectData;
		var statPool : Int32;
		var value : Float;
		var statusEffect : Variant;
		var statusEffectID : TweakDBID;
		var target : Entity;
		target = EffectExecutionScriptContext.GetTarget( applierCtx );
		puppet = ( ( ScriptedPuppet )( target ) );
		if( puppet )
		{
			data = EffectScriptContext.GetSharedData( ctx );
			EffectData.GetInt( data, GetAllBlackboardDefs().EffectSharedData.statType, statPool );
			EffectData.GetFloat( data, GetAllBlackboardDefs().EffectSharedData.value, value );
			EffectData.GetVariant( data, GetAllBlackboardDefs().EffectSharedData.statusEffect, statusEffect );
			statusEffectID = ( ( TweakDBID )statusEffect );
			GameInstance.GetStatusEffectSystem( puppet.GetGame() ).ApplyStatusEffect( puppet.GetEntityID(), statusEffectID );
			return true;
		}
		else
		{
		}
		return true;
	}

}

