enum MuramasaOption
{
	WheelCover = 0,
	WheelRims = 1,
	Branding = 2,
	BackRest = 3,
}

class CheckYaibaOption extends inkLogicController
{
	private editable var m_checkBox : inkWidgetRef;
	private editable var m_checkMark : inkWidgetRef;
	private editable var m_option : MuramasaOption;
	private var m_defaultOpacity : Float;
	private var m_isChecked : Bool;
	default m_isChecked = false;
	private var m_isHovered : Bool;
	default m_isHovered = false;
	private var m_isEnabled : Bool;
	default m_isEnabled = false;
	private var m_previewController : weak< YaibaOptionPreview >;

	public function Initialize( gameInstance : GameInstance, preview : weak< inkWidget >, fact : CName )
	{
		m_defaultOpacity = inkWidgetRef.GetOpacity( m_checkBox );
		RegisterToCallback( 'OnHoverOver', this, 'OnHoverOver' );
		RegisterToCallback( 'OnHoverOut', this, 'OnHoverOut' );
		RegisterToCallback( 'OnRelease', this, 'OnRelease' );
		m_isChecked = GetFact( gameInstance, fact ) == 1;
		m_previewController = ( ( YaibaOptionPreview )( preview.GetController() ) );
		m_previewController.SetActive( m_isChecked );
		RefreshVisibility();
	}

	public function Uninitialize()
	{
		UnregisterFromCallback( 'OnHoverOver', this, 'OnHoverOver' );
		UnregisterFromCallback( 'OnHoverOut', this, 'OnHoverOut' );
		UnregisterFromCallback( 'OnRelease', this, 'OnRelease' );
	}

	public function SetEnabled( enabled : Bool )
	{
		m_isEnabled = enabled;
		RefreshVisibility();
	}

	protected event OnHoverOver( e : inkPointerEvent )
	{
		if( !( m_isEnabled ) || e.IsHandled() )
		{
			return false;
		}
		m_previewController.SetHovered( true );
		m_isHovered = true;
		RefreshVisibility();
	}

	protected event OnHoverOut( e : inkPointerEvent )
	{
		if( !( m_isEnabled ) || e.IsHandled() )
		{
			return false;
		}
		m_previewController.SetHovered( false );
		m_isHovered = false;
		RefreshVisibility();
	}

	protected event OnRelease( e : inkPointerEvent )
	{
		if( ( !( m_isEnabled ) || m_previewController.IsAnimated() ) || e.IsHandled() )
		{
			return false;
		}
		if( e.IsAction( 'click' ) )
		{
			m_isChecked = !( m_isChecked );
			m_previewController.SetActive( m_isChecked );
			RefreshVisibility();
			CallCustomCallback( 'OnValueChanged' );
			e.Handle();
		}
	}

	private function RefreshVisibility()
	{
		inkWidgetRef.SetVisible( m_checkMark, m_isChecked || m_isHovered );
		inkWidgetRef.SetOpacity( m_checkBox, ( ( m_isEnabled && m_isHovered ) ? ( 1.0 ) : ( m_defaultOpacity ) ) );
	}

	public function IsChecked() : Bool
	{
		return m_isChecked;
	}

	public function IsHovered() : Bool
	{
		return m_isHovered;
	}

	public function GetOption() : MuramasaOption
	{
		return m_option;
	}

	public const function GetSelectionAnim() : CName
	{
		return m_previewController.GetSelectionAnim();
	}

	public const function GetRemovalAnim() : CName
	{
		return m_previewController.GetRemovalAnim();
	}

}

class YaibaOptionPreview extends inkLogicController
{
	private editable var m_selectionPreviewRef : inkWidgetRef;
	private editable var m_removalPreviewRef : inkWidgetRef;
	private editable var m_selectionAnimName : CName;
	private editable var m_removalAnimName : CName;
	private var m_active : Bool;
	private var m_isAnimated : Bool;
	default m_isAnimated = false;
	private var m_proxy : inkAnimProxy;

	public function SetHovered( hovered : Bool )
	{
		if( m_active )
		{
			inkWidgetRef.SetVisible( m_selectionPreviewRef, false );
			inkWidgetRef.SetVisible( m_removalPreviewRef, hovered );
		}
		else
		{
			inkWidgetRef.SetVisible( m_selectionPreviewRef, hovered );
			inkWidgetRef.SetVisible( m_removalPreviewRef, false );
		}
	}

	public function SetActive( active : Bool, optional force : Bool )
	{
		if( !( force ) && active == m_active )
		{
			return;
		}
		m_active = active;
		m_proxy = PlayLibraryAnimation( ( ( m_active ) ? ( m_selectionAnimName ) : ( m_removalAnimName ) ) );
		m_proxy.RegisterToCallback( inkanimEventType.OnFinish, this, 'OnAnimFinished' );
		m_isAnimated = true;
		SetHovered( false );
	}

	protected event OnAnimFinished( proxy : inkAnimProxy )
	{
		m_isAnimated = false;
	}

	public const function IsAnimated() : Bool
	{
		return m_isAnimated;
	}

	public const function GetSelectionAnim() : CName
	{
		return m_selectionAnimName;
	}

	public const function GetRemovalAnim() : CName
	{
		return m_removalAnimName;
	}

}

class YaibaButton extends inkButtonController
{
	private editable var m_normalBackground : inkImageRef;
	private editable var m_pressBackground : inkImageRef;
	private editable var m_hoverBackground : inkImageRef;
	private editable var m_disabledBackground : inkImageRef;
	private editable var m_enabledText : inkTextRef;
	private editable var m_disabledText : inkTextRef;

	protected event OnInitialize()
	{
		inkImageRef.SetVisible( m_normalBackground, true );
		inkImageRef.SetVisible( m_hoverBackground, false );
		inkImageRef.SetVisible( m_disabledBackground, false );
		inkTextRef.SetVisible( m_enabledText, true );
		inkTextRef.SetVisible( m_disabledText, false );
	}

	protected event OnButtonStateChanged( controller : weak< inkButtonController >, oldState : inkEButtonState, newState : inkEButtonState )
	{
		var isEnabled : Bool;
		inkImageRef.SetVisible( m_normalBackground, false );
		inkImageRef.SetVisible( m_pressBackground, false );
		inkImageRef.SetVisible( m_hoverBackground, false );
		inkImageRef.SetVisible( m_disabledBackground, false );
		switch( newState )
		{
			case inkEButtonState.Normal:
				inkImageRef.SetVisible( m_normalBackground, true );
			break;
			case inkEButtonState.Press:
				SetImageOrDefaultVisible( m_pressBackground, true, m_normalBackground );
			break;
			case inkEButtonState.Hover:
				SetImageOrDefaultVisible( m_hoverBackground, true, m_normalBackground );
			break;
			case inkEButtonState.Disabled:
				SetImageOrDefaultVisible( m_disabledBackground, true, m_normalBackground );
			break;
		}
		if( inkTextRef.IsValid( m_enabledText ) && inkTextRef.IsValid( m_disabledText ) )
		{
			isEnabled = newState != inkEButtonState.Disabled;
			inkTextRef.SetVisible( m_enabledText, isEnabled );
			inkTextRef.SetVisible( m_disabledText, !( isEnabled ) );
		}
	}

	private function SetImageOrDefaultVisible( image : inkImageRef, visible : Bool, defaultImage : inkImageRef )
	{
		if( inkImageRef.IsValid( image ) )
		{
			inkImageRef.SetVisible( image, true );
		}
		else
		{
			inkImageRef.SetVisible( defaultImage, true );
		}
	}

}

class ComputerYaibaShowroomController extends inkGameController
{
	[ category = "Settings" ]
	private editable var m_orderedFact : CName;
	[ category = "Settings" ]
	private editable var m_toBuyPageAnim : CName;
	[ category = "Webpage" ]
	protected editable var m_modelText : inkTextRef;
	[ category = "Webpage" ]
	protected editable var m_homePage : inkWidgetRef;
	[ category = "Webpage" ]
	protected editable var m_buyButton : inkWidgetRef;
	[ category = "Webpage" ]
	protected editable var m_buyPage : inkWidgetRef;
	[ category = "Webpage" ]
	protected editable var m_playerBalanceText : inkTextRef;
	[ category = "Webpage" ]
	protected editable var m_detailsCanvas : inkWidgetRef;
	[ category = "Webpage" ]
	protected editable var m_speedometer : inkImageRef;
	[ category = "Offer" ]
	protected editable var m_orderButton : inkWidgetRef;
	[ category = "Offer" ]
	protected editable var m_backButton : inkWidgetRef;
	[ category = "Check Box" ]
	private editable var m_wheelCoverCheckBox : inkWidgetRef;
	[ category = "Check Box" ]
	private editable var m_wheelRimsCheckBox : inkWidgetRef;
	[ category = "Check Box" ]
	private editable var m_brandingCheckBox : inkWidgetRef;
	[ category = "Check Box" ]
	private editable var m_backRestCheckBox : inkWidgetRef;
	[ category = "Preview" ]
	private editable var m_wheelCoverPreview : inkWidgetRef;
	[ category = "Preview" ]
	private editable var m_wheelRimsPreview : inkWidgetRef;
	[ category = "Preview" ]
	private editable var m_brandingPreview : inkWidgetRef;
	[ category = "Preview" ]
	private editable var m_backRestPreview : inkWidgetRef;
	private var m_inventoryListener : InventoryScriptListener;
	private var m_orderButtonController : weak< YaibaButton >;
	private var m_backButtonController : weak< YaibaButton >;
	private var m_wheelCoverCheckController : weak< CheckYaibaOption >;
	private var m_wheelRimsCheckController : weak< CheckYaibaOption >;
	private var m_brandingCheckController : weak< CheckYaibaOption >;
	private var m_backRestCheckController : weak< CheckYaibaOption >;
	private var m_wheelCoverFact : CName;
	default m_wheelCoverFact = 'mq060_muramasa_wheel_cover';
	private var m_WheelRimsFact : CName;
	default m_WheelRimsFact = 'mq060_muramasa_wheel_rims';
	private var m_BrandingFact : CName;
	default m_BrandingFact = 'mq060_muramasa_branding';
	private var m_BackRestFact : CName;
	default m_BackRestFact = 'mq060_muramasa_back_rest';
	private var m_isAnimated : Bool;
	private var m_settings : UserSettings;

	protected event OnInitialize()
	{
		var isVehicleAvailable : Bool;
		var isAvailable : Bool;
		var speedunitsVar : ConfigVarListString;
		isAvailable = CheckAvailability();
		RefreshModelText();
		inkWidgetRef.RegisterToCallback( m_buyButton, 'OnRelease', this, 'OnReleaseBuyButton' );
		isVehicleAvailable = isAvailable;
		m_orderButtonController = ( ( YaibaButton )( inkWidgetRef.GetController( m_orderButton ) ) );
		m_orderButtonController.RegisterToCallback( 'OnRelease', this, 'OnOrderRelease' );
		m_orderButtonController.SetEnabled( isAvailable );
		m_backButtonController = ( ( YaibaButton )( inkWidgetRef.GetController( m_backButton ) ) );
		m_backButtonController.RegisterToCallback( 'OnRelease', this, 'OnBackRelease' );
		m_wheelCoverCheckController = InitCheckBox( m_wheelCoverCheckBox, isVehicleAvailable, inkWidgetRef.Get( m_wheelCoverPreview ), m_wheelCoverFact );
		m_wheelRimsCheckController = InitCheckBox( m_wheelRimsCheckBox, isVehicleAvailable, inkWidgetRef.Get( m_wheelRimsPreview ), m_WheelRimsFact );
		m_brandingCheckController = InitCheckBox( m_brandingCheckBox, isVehicleAvailable, inkWidgetRef.Get( m_brandingPreview ), m_BrandingFact );
		m_backRestCheckController = InitCheckBox( m_backRestCheckBox, isVehicleAvailable, inkWidgetRef.Get( m_backRestPreview ), m_BackRestFact );
		m_settings = GetSystemRequestsHandler().GetUserSettings();
		speedunitsVar = ( ( ConfigVarListString )( m_settings.GetVar( '/interface', 'SpeedometerUnits' ) ) );
		switch( speedunitsVar.GetIndex() )
		{
			case 0:
				inkImageRef.SetTexturePart( m_speedometer, 'muramasa_maxspeed_kph' );
			break;
			case 1:
				inkImageRef.SetTexturePart( m_speedometer, 'muramasa_maxspeed_mph' );
			break;
		}
	}

	protected event OnReleaseBuyButton( e : inkPointerEvent )
	{
		if( m_isAnimated )
		{
			return false;
		}
		if( e.IsAction( 'click' ) )
		{
			SwitchToBuyPage();
			e.Handle();
		}
	}

	protected event OnBackRelease( e : inkPointerEvent )
	{
		if( m_isAnimated )
		{
			return false;
		}
		if( e.IsAction( 'click' ) )
		{
			SwitchToHomePage();
			e.Handle();
		}
	}

	protected event OnAnimFinished( proxy : inkAnimProxy )
	{
		m_isAnimated = false;
	}

	protected event OnCheckChanged( checkBox : weak< inkWidget > )
	{
		RefreshModelText();
	}

	protected event OnOrderRelease( e : inkPointerEvent )
	{
		if( m_isAnimated )
		{
			return false;
		}
		if( e.IsAction( 'click' ) )
		{
			if( CheckAvailability() )
			{
				SetFact( m_wheelCoverFact, ( ( m_wheelCoverCheckController.IsChecked() ) ? ( 1 ) : ( 0 ) ) );
				SetFact( m_WheelRimsFact, ( ( m_wheelRimsCheckController.IsChecked() ) ? ( 1 ) : ( 0 ) ) );
				SetFact( m_BrandingFact, ( ( m_brandingCheckController.IsChecked() ) ? ( 1 ) : ( 0 ) ) );
				SetFact( m_BackRestFact, ( ( m_backRestCheckController.IsChecked() ) ? ( 1 ) : ( 0 ) ) );
				SetFact( m_orderedFact, 1 );
				OnOrdered();
			}
		}
	}

	private function InitCheckBox( checkBox : inkWidgetRef, isEnabled : Bool, preview : weak< inkWidget >, fact : CName ) : weak< CheckYaibaOption >
	{
		var controller : weak< CheckYaibaOption >;
		controller = ( ( CheckYaibaOption )( inkWidgetRef.GetController( checkBox ) ) );
		controller.Initialize( ( ( GameObject )( GetOwnerEntity() ) ).GetGame(), preview, fact );
		controller.SetEnabled( isEnabled );
		controller.RegisterToCallback( 'OnValueChanged', this, 'OnCheckChanged' );
		return controller;
	}

	private function RefreshModelText()
	{
		var text : String;
		text = GetLocalizedTextByKey( 'Story-base-journal-onscreens-emails-quests-minor_quest-mq060-terminal-Mq060_terminal_Muramasa_subtitle_codename' );
		text += " - ";
		text += ( ( m_wheelCoverCheckController.IsChecked() ) ? ( "1" ) : ( "0" ) );
		text += ( ( m_wheelRimsCheckController.IsChecked() ) ? ( "1" ) : ( "0" ) );
		text += ( ( m_brandingCheckController.IsChecked() ) ? ( "1" ) : ( "0" ) );
		text += ( ( m_backRestCheckController.IsChecked() ) ? ( "1" ) : ( "0" ) );
		inkTextRef.SetText( m_modelText, text );
	}

	private function SwitchToHomePage()
	{
		var options : inkAnimOptions;
		options.playReversed = true;
		PlayLibraryAnimation( m_toBuyPageAnim, options ).RegisterToCallback( inkanimEventType.OnFinish, this, 'OnAnimFinished' );
		m_isAnimated = true;
	}

	private function SwitchToBuyPage()
	{
		PlayLibraryAnimation( m_toBuyPageAnim ).RegisterToCallback( inkanimEventType.OnFinish, this, 'OnAnimFinished' );
		m_isAnimated = true;
	}

	public function CheckAvailability() : Bool
	{
		return GetFact( GetGame(), m_orderedFact ) == 0;
	}

	public function SetFact( factName : CName, factCount : Int32 ) : Bool
	{
		return SetFactValue( GetGame(), factName, factCount );
	}

	protected function GetGame() : GameInstance
	{
		var gameInstance : GameInstance;
		var gameObject : GameObject;
		gameObject = ( ( GameObject )( GetOwnerEntity() ) );
		if( gameObject )
		{
			gameInstance = gameObject.GetGame();
		}
		return gameInstance;
	}

	private function GetPlayerMoney() : Int32
	{
		var gi : GameInstance;
		var player : PlayerPuppet;
		var transactionSystem : TransactionSystem;
		gi = GetGame();
		player = ( ( PlayerPuppet )( GameInstance.GetPlayerSystem( gi ).GetLocalPlayerControlledGameObject() ) );
		transactionSystem = GameInstance.GetTransactionSystem( gi );
		return transactionSystem.GetItemQuantity( player, MarketSystem.Money() );
	}

	private function RemovePlayerMoney( amount : Int32 ) : Bool
	{
		var gi : GameInstance;
		var player : PlayerPuppet;
		var transactionSystem : TransactionSystem;
		gi = GetGame();
		player = ( ( PlayerPuppet )( GameInstance.GetPlayerSystem( gi ).GetLocalPlayerControlledGameObject() ) );
		transactionSystem = GameInstance.GetTransactionSystem( gi );
		return transactionSystem.RemoveItem( player, MarketSystem.Money(), amount );
	}

	private function OnOrdered()
	{
		m_wheelCoverCheckController.SetEnabled( false );
		m_wheelRimsCheckController.SetEnabled( false );
		m_brandingCheckController.SetEnabled( false );
		m_backRestCheckController.SetEnabled( false );
		m_orderButtonController.SetEnabled( false );
		ShowNotification();
	}

	private function ShowNotification()
	{
		PlayLibraryAnimation( 'notification_anim' );
	}

}

