class SignInPopupEvent extends Event
{
}

class SignInPopupData extends inkGameNotificationData
{
}

class SignInPopupController extends BaseGOGProfileController
{
	private editable var m_qrCodeContainerRef : inkWidgetRef;
	private editable var m_qrImageWidgetRef : inkImageRef;
	private editable var m_hyperlinkButtonRef : inkWidgetRef;
	private editable var m_closeButtonRef : inkWidgetRef;
	private editable var m_introAnimationName : CName;
	private var m_data : SignInPopupData;
	private var m_requestHandler : weak< inkISystemRequestsHandler >;
	private var m_introAnimProxy : inkAnimProxy;
	private var m_signinUrl : String;
	private var m_signInQrCodeController : weak< SignInQrCodeController >;

	protected event OnInitialize()
	{
		m_data = ( ( SignInPopupData )( GetRootWidget().GetUserData( 'SignInPopupData' ) ) );
		m_requestHandler = GetSystemRequestsHandler();
		m_signInQrCodeController = ( ( SignInQrCodeController )( inkWidgetRef.GetController( m_qrCodeContainerRef ) ) );
		RegisterToGlobalInputCallback( 'OnPostOnRelease', this, 'OnRelease' );
		if( GetPlatformShortName() == "windows" )
		{
			inkWidgetRef.SetVisible( m_hyperlinkButtonRef, true );
			inkWidgetRef.RegisterToCallback( m_hyperlinkButtonRef, 'OnPress', this, 'OnPressHyperlink' );
		}
		else
		{
			inkWidgetRef.SetVisible( m_hyperlinkButtonRef, false );
		}
		inkWidgetRef.RegisterToCallback( m_closeButtonRef, 'OnPress', this, 'OnPressClose' );
		m_introAnimProxy = PlayLibraryAnimation( m_introAnimationName );
		PlaySound( 'GameMenu', 'OnOpen' );
	}

	protected event OnUninitialize()
	{
		UnregisterFromGlobalInputCallback( 'OnPostOnRelease', this, 'OnRelease' );
		if( GetPlatformShortName() == "windows" )
		{
			inkWidgetRef.UnregisterFromCallback( m_hyperlinkButtonRef, 'OnPress', this, 'OnPressHyperlink' );
		}
		inkWidgetRef.UnregisterFromCallback( m_closeButtonRef, 'OnPress', this, 'OnPressClose' );
	}

	private function Close()
	{
		var playbackOptions : inkAnimOptions;
		PlaySound( 'Button', 'OnPress' );
		playbackOptions.playReversed = true;
		m_introAnimProxy = PlayLibraryAnimation( m_introAnimationName, playbackOptions );
		m_introAnimProxy.RegisterToCallback( inkanimEventType.OnFinish, this, 'OnOutroAnimationFinished' );
	}

	protected event OnRefreshGOGState( evt : RefreshGOGState )
	{
		if( evt.status == GOGRewardsSystemStatus.RegistrationPending )
		{
			m_signinUrl = evt.registerURL;
			m_signInQrCodeController.UpdateQrCode( evt.qrCodePNGBlob );
		}
	}

	protected event OnRelease( evt : inkPointerEvent )
	{
		if( evt.IsAction( 'close_popup' ) && !( m_introAnimProxy.IsPlaying() ) )
		{
			Close();
		}
	}

	protected event OnPressHyperlink( evt : inkPointerEvent )
	{
		if( ( evt.IsAction( 'click' ) && !( m_introAnimProxy.IsPlaying() ) ) && m_signinUrl != "" )
		{
			OpenProfileUrl( m_signinUrl );
		}
	}

	protected event OnPressClose( evt : inkPointerEvent )
	{
		if( evt.IsAction( 'click' ) && !( m_introAnimProxy.IsPlaying() ) )
		{
			Close();
		}
	}

	protected event OnOutroAnimationFinished( proxy : inkAnimProxy )
	{
		m_introAnimProxy.UnregisterFromCallback( inkanimEventType.OnFinish, this, 'OnOutroAnimationFinished' );
		m_data.token.TriggerCallback( m_data );
	}

}

class SignInQrCodeController extends BaseGOGRegisterController
{
	private editable var m_qrImageWidgetRef : inkImageRef;
	private var m_qrImageWidget : weak< inkImage >;

	protected event OnInitialize()
	{
		m_qrImageWidget = ( ( inkImage )( inkImageRef.Get( m_qrImageWidgetRef ) ) );
	}

	public function UpdateQrCode( qrCodePNGBlob : array< Uint8 > )
	{
		SetupQRCodeWidget( m_qrImageWidget, qrCodePNGBlob );
	}

}

