class YaibaShowroomConnectionPage extends inkGameController
{
	private editable var m_connectionFact : CName;
	default m_connectionFact = 'mq060_muramasa_connected';
	private editable var m_connectionButton : inkWidgetRef;

	protected event OnInitialize()
	{
		inkWidgetRef.RegisterToCallback( m_connectionButton, 'OnRelease', this, 'OnRelease' );
	}

	protected event OnRelease( e : inkPointerEvent )
	{
		if( e.IsAction( 'click' ) )
		{
			SetFactValue( ( ( GameObject )( GetOwnerEntity() ) ).GetGame(), m_connectionFact, 1 );
		}
	}

}

