@replaceMethod(RPGManager)
  public final static func GetModsSlotIDs(type: gamedataItemType) -> [TweakDBID] {
    let arr: array<TweakDBID>;
    switch type {
      case gamedataItemType.Clo_Head:
        ArrayPush(arr, t"AttachmentSlots.HeadFabricEnhancer1");
        ArrayPush(arr, t"AttachmentSlots.HeadFabricEnhancer2");
        ArrayPush(arr, t"AttachmentSlots.HeadFabricEnhancer3");
        ArrayPush(arr, t"AttachmentSlots.HeadFabricEnhancer4");
        break;
      case gamedataItemType.Clo_Feet:
        ArrayPush(arr, t"AttachmentSlots.FootFabricEnhancer1");
        ArrayPush(arr, t"AttachmentSlots.FootFabricEnhancer2");
        ArrayPush(arr, t"AttachmentSlots.FootFabricEnhancer3");
        ArrayPush(arr, t"AttachmentSlots.FootFabricEnhancer4");
        break;
      case gamedataItemType.Clo_Face:
        ArrayPush(arr, t"AttachmentSlots.FaceFabricEnhancer1");
        ArrayPush(arr, t"AttachmentSlots.FaceFabricEnhancer2");
        ArrayPush(arr, t"AttachmentSlots.FaceFabricEnhancer3");
        ArrayPush(arr, t"AttachmentSlots.FaceFabricEnhancer4");
        break;
      case gamedataItemType.Clo_InnerChest:
        ArrayPush(arr, t"AttachmentSlots.InnerChestFabricEnhancer1");
        ArrayPush(arr, t"AttachmentSlots.InnerChestFabricEnhancer2");
        ArrayPush(arr, t"AttachmentSlots.InnerChestFabricEnhancer3");
        break;
      case gamedataItemType.Clo_Legs:
        ArrayPush(arr, t"AttachmentSlots.LegsFabricEnhancer1");
        ArrayPush(arr, t"AttachmentSlots.LegsFabricEnhancer2");
        ArrayPush(arr, t"AttachmentSlots.LegsFabricEnhancer3");
        ArrayPush(arr, t"AttachmentSlots.LegsFabricEnhancer4");
        break;
      case gamedataItemType.Clo_OuterChest:
        ArrayPush(arr, t"AttachmentSlots.OuterChestFabricEnhancer1");
        ArrayPush(arr, t"AttachmentSlots.OuterChestFabricEnhancer2");
        ArrayPush(arr, t"AttachmentSlots.OuterChestFabricEnhancer3");
        break;
      case gamedataItemType.Wea_LightMachineGun:
      case gamedataItemType.Wea_SubmachineGun:
      case gamedataItemType.Wea_Rifle:
      case gamedataItemType.Wea_AssaultRifle:
        ArrayPush(arr, t"AttachmentSlots.Power_AR_SMG_LMG_WeaponMod1");
        ArrayPush(arr, t"AttachmentSlots.Power_AR_SMG_LMG_WeaponMod2");
        ArrayPush(arr, t"AttachmentSlots.Power_AR_SMG_LMG_WeaponMod1_Collectible");
        ArrayPush(arr, t"AttachmentSlots.Power_AR_SMG_LMG_WeaponMod2_Collectible");
        ArrayPush(arr, t"AttachmentSlots.Tech_AR_SMG_LMG_WeaponMod1");
        ArrayPush(arr, t"AttachmentSlots.Tech_AR_SMG_LMG_WeaponMod2");
        ArrayPush(arr, t"AttachmentSlots.Smart_AR_SMG_LMG_WeaponMod1");
        ArrayPush(arr, t"AttachmentSlots.Smart_AR_SMG_LMG_WeaponMod2");
        ArrayPush(arr, t"AttachmentSlots.Power_AR_SMG_LMG_WeaponMod3");
        ArrayPush(arr, t"AttachmentSlots.Power_AR_SMG_LMG_WeaponMod4");
        ArrayPush(arr, t"AttachmentSlots.Power_AR_SMG_LMG_WeaponMod5");
        ArrayPush(arr, t"AttachmentSlots.Power_AR_SMG_LMG_WeaponMod6");
        ArrayPush(arr, t"AttachmentSlots.Tech_AR_SMG_LMG_WeaponMod3");
        ArrayPush(arr, t"AttachmentSlots.Tech_AR_SMG_LMG_WeaponMod4");
        ArrayPush(arr, t"AttachmentSlots.Tech_AR_SMG_LMG_WeaponMod5");
        ArrayPush(arr, t"AttachmentSlots.Tech_AR_SMG_LMG_WeaponMod6");
        ArrayPush(arr, t"AttachmentSlots.Smart_AR_SMG_LMG_WeaponMod3");
        ArrayPush(arr, t"AttachmentSlots.Smart_AR_SMG_LMG_WeaponMod4");
        ArrayPush(arr, t"AttachmentSlots.Smart_AR_SMG_LMG_WeaponMod5");
        ArrayPush(arr, t"AttachmentSlots.Smart_AR_SMG_LMG_WeaponMod6");
        ArrayPush(arr, t"AttachmentSlots.GenericWeaponMod1");
        ArrayPush(arr, t"AttachmentSlots.GenericWeaponMod2");
        ArrayPush(arr, t"AttachmentSlots.GenericWeaponMod3");
        ArrayPush(arr, t"AttachmentSlots.GenericWeaponMod4");
        ArrayPush(arr, t"AttachmentSlots.GenericWeaponMod5");
        ArrayPush(arr, t"AttachmentSlots.GenericWeaponMod6");
        return arr;
      case gamedataItemType.Wea_Revolver:
      case gamedataItemType.Wea_Handgun:
        ArrayPush(arr, t"AttachmentSlots.Power_Handgun_WeaponMod1");
        ArrayPush(arr, t"AttachmentSlots.Power_Handgun_WeaponMod2");
        ArrayPush(arr, t"AttachmentSlots.Power_Handgun_WeaponMod3");
        ArrayPush(arr, t"AttachmentSlots.Power_Handgun_WeaponMod4");
        ArrayPush(arr, t"AttachmentSlots.Power_Handgun_WeaponMod5");
        ArrayPush(arr, t"AttachmentSlots.Power_Handgun_WeaponMod6");
        ArrayPush(arr, t"AttachmentSlots.Smart_Handgun_WeaponMod3");
        ArrayPush(arr, t"AttachmentSlots.Smart_Handgun_WeaponMod4");
        ArrayPush(arr, t"AttachmentSlots.Smart_Handgun_WeaponMod5");
        ArrayPush(arr, t"AttachmentSlots.Smart_Handgun_WeaponMod6");
        ArrayPush(arr, t"AttachmentSlots.Tech_Handgun_WeaponMod3");
        ArrayPush(arr, t"AttachmentSlots.Tech_Handgun_WeaponMod4");
        ArrayPush(arr, t"AttachmentSlots.Tech_Handgun_WeaponMod5");
        ArrayPush(arr, t"AttachmentSlots.Tech_Handgun_WeaponMod6");
        ArrayPush(arr, t"AttachmentSlots.Power_Handgun_WeaponMod1_Collectible");
        ArrayPush(arr, t"AttachmentSlots.Power_Handgun_WeaponMod2_Collectible");
        ArrayPush(arr, t"AttachmentSlots.Tech_Handgun_WeaponMod1");
        ArrayPush(arr, t"AttachmentSlots.Tech_Handgun_WeaponMod2");
        ArrayPush(arr, t"AttachmentSlots.Smart_Handgun_WeaponMod1");
        ArrayPush(arr, t"AttachmentSlots.Smart_Handgun_WeaponMod2");
        ArrayPush(arr, t"AttachmentSlots.Smart_Handgun_WeaponMod1_Collectible");
        ArrayPush(arr, t"AttachmentSlots.Smart_Handgun_WeaponMod2_Collectible");
        ArrayPush(arr, t"AttachmentSlots.GenericWeaponMod1");
        ArrayPush(arr, t"AttachmentSlots.GenericWeaponMod2");
        ArrayPush(arr, t"AttachmentSlots.GenericWeaponMod3");
        ArrayPush(arr, t"AttachmentSlots.GenericWeaponMod4");
        ArrayPush(arr, t"AttachmentSlots.GenericWeaponMod5");
        ArrayPush(arr, t"AttachmentSlots.GenericWeaponMod6");
        return arr;
      case gamedataItemType.Wea_SniperRifle:
      case gamedataItemType.Wea_PrecisionRifle:
        ArrayPush(arr, t"AttachmentSlots.Power_Precision_Sniper_Rifle_WeaponMod1");
        ArrayPush(arr, t"AttachmentSlots.Power_Precision_Sniper_Rifle_WeaponMod2");
        ArrayPush(arr, t"AttachmentSlots.Tech_Precision_Sniper_Rifle_WeaponMod1");
        ArrayPush(arr, t"AttachmentSlots.Tech_Precision_Sniper_Rifle_WeaponMod2");
        ArrayPush(arr, t"AttachmentSlots.Tech_Precision_Sniper_Rifle_WeaponMod1_Collectible");
        ArrayPush(arr, t"AttachmentSlots.Tech_Precision_Sniper_Rifle_WeaponMod2_Collectible");
        ArrayPush(arr, t"AttachmentSlots.Smart_Precision_Sniper_Rifle_WeaponMod1");
        ArrayPush(arr, t"AttachmentSlots.Smart_Precision_Sniper_Rifle_WeaponMod2");
        ArrayPush(arr, t"AttachmentSlots.Power_Precision_Sniper_Rifle_WeaponMod3");
        ArrayPush(arr, t"AttachmentSlots.Power_Precision_Sniper_Rifle_WeaponMod4");
        ArrayPush(arr, t"AttachmentSlots.Power_Precision_Sniper_Rifle_WeaponMod5");
        ArrayPush(arr, t"AttachmentSlots.Power_Precision_Sniper_Rifle_WeaponMod6");
        ArrayPush(arr, t"AttachmentSlots.Tech_Precision_Sniper_Rifle_WeaponMod3");
        ArrayPush(arr, t"AttachmentSlots.Tech_Precision_Sniper_Rifle_WeaponMod4");
        ArrayPush(arr, t"AttachmentSlots.Tech_Precision_Sniper_Rifle_WeaponMod5");
        ArrayPush(arr, t"AttachmentSlots.Tech_Precision_Sniper_Rifle_WeaponMod6");
        ArrayPush(arr, t"AttachmentSlots.Smart_Precision_Sniper_Rifle_WeaponMod3");
        ArrayPush(arr, t"AttachmentSlots.Smart_Precision_Sniper_Rifle_WeaponMod4");
        ArrayPush(arr, t"AttachmentSlots.Smart_Precision_Sniper_Rifle_WeaponMod5");
        ArrayPush(arr, t"AttachmentSlots.Smart_Precision_Sniper_Rifle_WeaponMod6");
        ArrayPush(arr, t"AttachmentSlots.Smart_Precision_Sniper_Rifle_WeaponMod1_Collectible");
        ArrayPush(arr, t"AttachmentSlots.Smart_Precision_Sniper_Rifle_WeaponMod2_Collectible");
        ArrayPush(arr, t"AttachmentSlots.GenericWeaponMod1");
        ArrayPush(arr, t"AttachmentSlots.GenericWeaponMod2");
        ArrayPush(arr, t"AttachmentSlots.GenericWeaponMod3");
        ArrayPush(arr, t"AttachmentSlots.GenericWeaponMod4");
        ArrayPush(arr, t"AttachmentSlots.GenericWeaponMod5");
        ArrayPush(arr, t"AttachmentSlots.GenericWeaponMod6");
        return arr;
      case gamedataItemType.Cyb_Launcher:
      case gamedataItemType.Wea_ShotgunDual:
      case gamedataItemType.Wea_Shotgun:
        ArrayPush(arr, t"AttachmentSlots.Power_Shotgun_WeaponMod1");
        ArrayPush(arr, t"AttachmentSlots.Power_Shotgun_WeaponMod2");
        ArrayPush(arr, t"AttachmentSlots.Power_Shotgun_WeaponMod1_Collectible");
        ArrayPush(arr, t"AttachmentSlots.Power_Shotgun_WeaponMod2_Collectible");
        ArrayPush(arr, t"AttachmentSlots.Tech_Shotgun_WeaponMod1");
        ArrayPush(arr, t"AttachmentSlots.Tech_Shotgun_WeaponMod2");
        ArrayPush(arr, t"AttachmentSlots.Smart_Shotgun_WeaponMod1");
        ArrayPush(arr, t"AttachmentSlots.Smart_Shotgun_WeaponMod2");
        ArrayPush(arr, t"AttachmentSlots.Power_Shotgun_WeaponMod3");
        ArrayPush(arr, t"AttachmentSlots.Power_Shotgun_WeaponMod4");
        ArrayPush(arr, t"AttachmentSlots.Power_Shotgun_WeaponMod5");
        ArrayPush(arr, t"AttachmentSlots.Power_Shotgun_WeaponMod6");
        ArrayPush(arr, t"AttachmentSlots.Tech_Shotgun_WeaponMod3");
        ArrayPush(arr, t"AttachmentSlots.Tech_Shotgun_WeaponMod4");
        ArrayPush(arr, t"AttachmentSlots.Tech_Shotgun_WeaponMod5");
        ArrayPush(arr, t"AttachmentSlots.Tech_Shotgun_WeaponMod6");
        ArrayPush(arr, t"AttachmentSlots.Smart_Shotgun_WeaponMod3");
        ArrayPush(arr, t"AttachmentSlots.Smart_Shotgun_WeaponMod4");
        ArrayPush(arr, t"AttachmentSlots.Smart_Shotgun_WeaponMod5");
        ArrayPush(arr, t"AttachmentSlots.Smart_Shotgun_WeaponMod6"); 
        ArrayPush(arr, t"AttachmentSlots.GenericWeaponMod1");
        ArrayPush(arr, t"AttachmentSlots.GenericWeaponMod2");
        ArrayPush(arr, t"AttachmentSlots.GenericWeaponMod3");
        ArrayPush(arr, t"AttachmentSlots.GenericWeaponMod4");
        ArrayPush(arr, t"AttachmentSlots.GenericWeaponMod5");
        ArrayPush(arr, t"AttachmentSlots.GenericWeaponMod6");
        return arr;
      case gamedataItemType.Cyb_NanoWires:
      case gamedataItemType.Cyb_MantisBlades:
      case gamedataItemType.Wea_ShortBlade:
      case gamedataItemType.Wea_Machete:
      case gamedataItemType.Wea_LongBlade:
      case gamedataItemType.Wea_Sword:
      case gamedataItemType.Wea_Katana:
      case gamedataItemType.Wea_Chainsword:
        ArrayPush(arr, t"AttachmentSlots.Blade_WeaponMod1");
        ArrayPush(arr, t"AttachmentSlots.Blade_WeaponMod2");
        ArrayPush(arr, t"AttachmentSlots.Blade_WeaponMod3");
        ArrayPush(arr, t"AttachmentSlots.Blade_WeaponMod4");
        ArrayPush(arr, t"AttachmentSlots.Blade_WeaponMod5");
        ArrayPush(arr, t"AttachmentSlots.Blade_WeaponMod6");
        ArrayPush(arr, t"AttachmentSlots.Blade_WeaponMod1_Collectible");
        ArrayPush(arr, t"AttachmentSlots.Blade_WeaponMod2_Collectible");
        ArrayPush(arr, t"AttachmentSlots.MeleeWeaponMod1");
        ArrayPush(arr, t"AttachmentSlots.MeleeWeaponMod2");
        ArrayPush(arr, t"AttachmentSlots.MeleeWeaponMod3");
        ArrayPush(arr, t"AttachmentSlots.MeleeWeaponMod4");
        ArrayPush(arr, t"AttachmentSlots.MeleeWeaponMod5");
        ArrayPush(arr, t"AttachmentSlots.MeleeWeaponMod6");
        return arr;
      case gamedataItemType.Wea_Knife:
      case gamedataItemType.Wea_Axe:
        ArrayPush(arr, t"AttachmentSlots.Throwable_WeaponMod1");
        ArrayPush(arr, t"AttachmentSlots.Throwable_WeaponMod2");
        ArrayPush(arr, t"AttachmentSlots.Throwable_WeaponMod3");
        ArrayPush(arr, t"AttachmentSlots.Throwable_WeaponMod4");
        ArrayPush(arr, t"AttachmentSlots.Throwable_WeaponMod5");
        ArrayPush(arr, t"AttachmentSlots.Throwable_WeaponMod6");
        ArrayPush(arr, t"AttachmentSlots.Throwable_WeaponMod1_Collectible");
        ArrayPush(arr, t"AttachmentSlots.Throwable_WeaponMod2_Collectible");
        ArrayPush(arr, t"AttachmentSlots.MeleeWeaponMod1");
        ArrayPush(arr, t"AttachmentSlots.MeleeWeaponMod2");
        ArrayPush(arr, t"AttachmentSlots.MeleeWeaponMod3");
        ArrayPush(arr, t"AttachmentSlots.MeleeWeaponMod4");
        ArrayPush(arr, t"AttachmentSlots.MeleeWeaponMod5");
        ArrayPush(arr, t"AttachmentSlots.MeleeWeaponMod6");
        return arr;
      case gamedataItemType.Cyb_StrongArms:
      case gamedataItemType.Wea_TwoHandedClub:
      case gamedataItemType.Wea_OneHandedClub:
      case gamedataItemType.Wea_Hammer:
        ArrayPush(arr, t"AttachmentSlots.Blunt_WeaponMod1");
        ArrayPush(arr, t"AttachmentSlots.Blunt_WeaponMod2");
        ArrayPush(arr, t"AttachmentSlots.Blunt_WeaponMod3");
        ArrayPush(arr, t"AttachmentSlots.Blunt_WeaponMod4");
        ArrayPush(arr, t"AttachmentSlots.Blunt_WeaponMod5");
        ArrayPush(arr, t"AttachmentSlots.Blunt_WeaponMod6");
        ArrayPush(arr, t"AttachmentSlots.Blunt_WeaponMod1_Collectible");
        ArrayPush(arr, t"AttachmentSlots.Blunt_WeaponMod2_Collectible");
        ArrayPush(arr, t"AttachmentSlots.MeleeWeaponMod1");
        ArrayPush(arr, t"AttachmentSlots.MeleeWeaponMod2");
        ArrayPush(arr, t"AttachmentSlots.MeleeWeaponMod3");
        ArrayPush(arr, t"AttachmentSlots.MeleeWeaponMod4");
        ArrayPush(arr, t"AttachmentSlots.MeleeWeaponMod5");
        ArrayPush(arr, t"AttachmentSlots.MeleeWeaponMod6");
        return arr;
    };
    return arr;
  }

@replaceMethod(UIInventoryItemModsStaticData)
  public final static func GetAttachmentSlots(itemType: gamedataItemType) -> [TweakDBID] {
    let slots: array<TweakDBID>;
    switch itemType {
      case gamedataItemType.Clo_Head:
        ArrayPush(slots, t"AttachmentSlots.HeadFabricEnhancer1");
        ArrayPush(slots, t"AttachmentSlots.HeadFabricEnhancer2");
        ArrayPush(slots, t"AttachmentSlots.HeadFabricEnhancer3");
        break;
      case gamedataItemType.Clo_Face:
        ArrayPush(slots, t"AttachmentSlots.FaceFabricEnhancer1");
        ArrayPush(slots, t"AttachmentSlots.FaceFabricEnhancer2");
        ArrayPush(slots, t"AttachmentSlots.FaceFabricEnhancer3");
        break;
      case gamedataItemType.Clo_OuterChest:
        ArrayPush(slots, t"AttachmentSlots.OuterChestFabricEnhancer1");
        ArrayPush(slots, t"AttachmentSlots.OuterChestFabricEnhancer2");
        ArrayPush(slots, t"AttachmentSlots.OuterChestFabricEnhancer3");
        ArrayPush(slots, t"AttachmentSlots.OuterChestFabricEnhancer4");
        break;
      case gamedataItemType.Clo_InnerChest:
        ArrayPush(slots, t"AttachmentSlots.InnerChestFabricEnhancer1");
        ArrayPush(slots, t"AttachmentSlots.InnerChestFabricEnhancer2");
        ArrayPush(slots, t"AttachmentSlots.InnerChestFabricEnhancer3");
        ArrayPush(slots, t"AttachmentSlots.InnerChestFabricEnhancer4");
        break;
      case gamedataItemType.Clo_Legs:
        ArrayPush(slots, t"AttachmentSlots.LegsFabricEnhancer1");
        ArrayPush(slots, t"AttachmentSlots.LegsFabricEnhancer2");
        ArrayPush(slots, t"AttachmentSlots.LegsFabricEnhancer3");
        break;
      case gamedataItemType.Clo_Feet:
        ArrayPush(slots, t"AttachmentSlots.FootFabricEnhancer1");
        ArrayPush(slots, t"AttachmentSlots.FootFabricEnhancer2");
        ArrayPush(slots, t"AttachmentSlots.FootFabricEnhancer3");
        break;
      case gamedataItemType.Cyb_Launcher:
      case gamedataItemType.Wea_AssaultRifle:
      case gamedataItemType.Wea_Handgun:
      case gamedataItemType.Wea_SubmachineGun:
      case gamedataItemType.Wea_SniperRifle:
      case gamedataItemType.Wea_ShotgunDual:
      case gamedataItemType.Wea_Shotgun:
      case gamedataItemType.Wea_Rifle:
      case gamedataItemType.Wea_Revolver:
      case gamedataItemType.Wea_PrecisionRifle:
      case gamedataItemType.Wea_LightMachineGun:
      case gamedataItemType.Wea_HeavyMachineGun:
        ArrayPush(slots, t"AttachmentSlots.Scope");
        ArrayPush(slots, t"AttachmentSlots.PowerModule");
        ArrayPush(slots, t"AttachmentSlots.Power_AR_SMG_LMG_WeaponMod1");
        ArrayPush(slots, t"AttachmentSlots.Power_AR_SMG_LMG_WeaponMod2");
        ArrayPush(slots, t"AttachmentSlots.Power_AR_SMG_LMG_WeaponMod1_Collectible");
        ArrayPush(slots, t"AttachmentSlots.Power_AR_SMG_LMG_WeaponMod2_Collectible");
        ArrayPush(slots, t"AttachmentSlots.Tech_AR_SMG_LMG_WeaponMod1");
        ArrayPush(slots, t"AttachmentSlots.Tech_AR_SMG_LMG_WeaponMod2");
        ArrayPush(slots, t"AttachmentSlots.Smart_AR_SMG_LMG_WeaponMod1");
        ArrayPush(slots, t"AttachmentSlots.Smart_AR_SMG_LMG_WeaponMod2");
        ArrayPush(slots, t"AttachmentSlots.Power_Handgun_WeaponMod1");
        ArrayPush(slots, t"AttachmentSlots.Power_Handgun_WeaponMod2");
        ArrayPush(slots, t"AttachmentSlots.Power_Handgun_WeaponMod3");
        ArrayPush(slots, t"AttachmentSlots.Power_Handgun_WeaponMod4");
        ArrayPush(slots, t"AttachmentSlots.Power_Handgun_WeaponMod5");
        ArrayPush(slots, t"AttachmentSlots.Power_Handgun_WeaponMod6");
        ArrayPush(slots, t"AttachmentSlots.Smart_Handgun_WeaponMod3");
        ArrayPush(slots, t"AttachmentSlots.Smart_Handgun_WeaponMod4");
        ArrayPush(slots, t"AttachmentSlots.Smart_Handgun_WeaponMod5");
        ArrayPush(slots, t"AttachmentSlots.Smart_Handgun_WeaponMod6");
        ArrayPush(slots, t"AttachmentSlots.Tech_Handgun_WeaponMod3");
        ArrayPush(slots, t"AttachmentSlots.Tech_Handgun_WeaponMod4");
        ArrayPush(slots, t"AttachmentSlots.Tech_Handgun_WeaponMod5");
        ArrayPush(slots, t"AttachmentSlots.Tech_Handgun_WeaponMod6");
        ArrayPush(slots, t"AttachmentSlots.Power_AR_SMG_LMG_WeaponMod3");
        ArrayPush(slots, t"AttachmentSlots.Power_AR_SMG_LMG_WeaponMod4");
        ArrayPush(slots, t"AttachmentSlots.Power_AR_SMG_LMG_WeaponMod5");
        ArrayPush(slots, t"AttachmentSlots.Power_AR_SMG_LMG_WeaponMod6");
        ArrayPush(slots, t"AttachmentSlots.Smart_AR_SMG_LMG_WeaponMod3");
        ArrayPush(slots, t"AttachmentSlots.Smart_AR_SMG_LMG_WeaponMod4");
        ArrayPush(slots, t"AttachmentSlots.Smart_AR_SMG_LMG_WeaponMod5");
        ArrayPush(slots, t"AttachmentSlots.Smart_AR_SMG_LMG_WeaponMod6");
        ArrayPush(slots, t"AttachmentSlots.Tech_AR_SMG_LMG_WeaponMod3");
        ArrayPush(slots, t"AttachmentSlots.Tech_AR_SMG_LMG_WeaponMod4");
        ArrayPush(slots, t"AttachmentSlots.Tech_AR_SMG_LMG_WeaponMod5");
        ArrayPush(slots, t"AttachmentSlots.Tech_AR_SMG_LMG_WeaponMod6");
        ArrayPush(slots, t"AttachmentSlots.Power_Precision_Sniper_Rifle_WeaponMod3");
        ArrayPush(slots, t"AttachmentSlots.Power_Precision_Sniper_Rifle_WeaponMod4");
        ArrayPush(slots, t"AttachmentSlots.Power_Precision_Sniper_Rifle_WeaponMod5");
        ArrayPush(slots, t"AttachmentSlots.Power_Precision_Sniper_Rifle_WeaponMod6");
        ArrayPush(slots, t"AttachmentSlots.Smart_Precision_Sniper_Rifle_WeaponMod3");
        ArrayPush(slots, t"AttachmentSlots.Smart_Precision_Sniper_Rifle_WeaponMod4");
        ArrayPush(slots, t"AttachmentSlots.Smart_Precision_Sniper_Rifle_WeaponMod5");
        ArrayPush(slots, t"AttachmentSlots.Smart_Precision_Sniper_Rifle_WeaponMod6");
        ArrayPush(slots, t"AttachmentSlots.Tech_Precision_Sniper_Rifle_WeaponMod3");
        ArrayPush(slots, t"AttachmentSlots.Tech_Precision_Sniper_Rifle_WeaponMod4");
        ArrayPush(slots, t"AttachmentSlots.Tech_Precision_Sniper_Rifle_WeaponMod5");
        ArrayPush(slots, t"AttachmentSlots.Tech_Precision_Sniper_Rifle_WeaponMod6");
        ArrayPush(slots, t"AttachmentSlots.Power_Shotgun_WeaponMod3");
        ArrayPush(slots, t"AttachmentSlots.Power_Shotgun_WeaponMod4");
        ArrayPush(slots, t"AttachmentSlots.Power_Shotgun_WeaponMod5");
        ArrayPush(slots, t"AttachmentSlots.Power_Shotgun_WeaponMod6");
        ArrayPush(slots, t"AttachmentSlots.Smart_Shotgun_WeaponMod3");
        ArrayPush(slots, t"AttachmentSlots.Smart_Shotgun_WeaponMod4");
        ArrayPush(slots, t"AttachmentSlots.Smart_Shotgun_WeaponMod5");
        ArrayPush(slots, t"AttachmentSlots.Smart_Shotgun_WeaponMod6");
        ArrayPush(slots, t"AttachmentSlots.Tech_Shotgun_WeaponMod3");
        ArrayPush(slots, t"AttachmentSlots.Tech_Shotgun_WeaponMod4");
        ArrayPush(slots, t"AttachmentSlots.Tech_Shotgun_WeaponMod5");
        ArrayPush(slots, t"AttachmentSlots.Tech_Shotgun_WeaponMod6");
        ArrayPush(slots, t"AttachmentSlots.Power_Handgun_WeaponMod1_Collectible");
        ArrayPush(slots, t"AttachmentSlots.Power_Handgun_WeaponMod2_Collectible");
        ArrayPush(slots, t"AttachmentSlots.Tech_Handgun_WeaponMod1");
        ArrayPush(slots, t"AttachmentSlots.Tech_Handgun_WeaponMod2");
        ArrayPush(slots, t"AttachmentSlots.Smart_Handgun_WeaponMod1");
        ArrayPush(slots, t"AttachmentSlots.Smart_Handgun_WeaponMod2");
        ArrayPush(slots, t"AttachmentSlots.Smart_Handgun_WeaponMod1_Collectible");
        ArrayPush(slots, t"AttachmentSlots.Smart_Handgun_WeaponMod2_Collectible");
        ArrayPush(slots, t"AttachmentSlots.Power_Precision_Sniper_Rifle_WeaponMod1");
        ArrayPush(slots, t"AttachmentSlots.Power_Precision_Sniper_Rifle_WeaponMod2");
        ArrayPush(slots, t"AttachmentSlots.Tech_Precision_Sniper_Rifle_WeaponMod1");
        ArrayPush(slots, t"AttachmentSlots.Tech_Precision_Sniper_Rifle_WeaponMod2");
        ArrayPush(slots, t"AttachmentSlots.Tech_Precision_Sniper_Rifle_WeaponMod1_Collectible");
        ArrayPush(slots, t"AttachmentSlots.Tech_Precision_Sniper_Rifle_WeaponMod2_Collectible");
        ArrayPush(slots, t"AttachmentSlots.Smart_Precision_Sniper_Rifle_WeaponMod1");
        ArrayPush(slots, t"AttachmentSlots.Smart_Precision_Sniper_Rifle_WeaponMod2");
        ArrayPush(slots, t"AttachmentSlots.Smart_Precision_Sniper_Rifle_WeaponMod1_Collectible");
        ArrayPush(slots, t"AttachmentSlots.Smart_Precision_Sniper_Rifle_WeaponMod2_Collectible");
        ArrayPush(slots, t"AttachmentSlots.Power_Shotgun_WeaponMod1");
        ArrayPush(slots, t"AttachmentSlots.Power_Shotgun_WeaponMod2");
        ArrayPush(slots, t"AttachmentSlots.Power_Shotgun_WeaponMod1_Collectible");
        ArrayPush(slots, t"AttachmentSlots.Power_Shotgun_WeaponMod2_Collectible");
        ArrayPush(slots, t"AttachmentSlots.Tech_Shotgun_WeaponMod1");
        ArrayPush(slots, t"AttachmentSlots.Tech_Shotgun_WeaponMod2");
        ArrayPush(slots, t"AttachmentSlots.Smart_Shotgun_WeaponMod1");
        ArrayPush(slots, t"AttachmentSlots.Smart_Shotgun_WeaponMod2");
        ArrayPush(slots, t"AttachmentSlots.IconicWeaponModLegendary");
        break;
      case gamedataItemType.Cyb_NanoWires:
      case gamedataItemType.Cyb_MantisBlades:
      case gamedataItemType.Cyb_StrongArms:
      case gamedataItemType.Wea_Machete:
      case gamedataItemType.Wea_Chainsword:
      case gamedataItemType.Wea_Axe:
      case gamedataItemType.Wea_Knife:
      case gamedataItemType.Wea_Sword:
      case gamedataItemType.Wea_Katana:
      case gamedataItemType.Wea_Melee:
      case gamedataItemType.Wea_LongBlade:
      case gamedataItemType.Wea_OneHandedClub:
      case gamedataItemType.Wea_ShortBlade:
      case gamedataItemType.Wea_Hammer:
      case gamedataItemType.Wea_TwoHandedClub:
      case gamedataItemType.Wea_Fists:
        ArrayPush(slots, t"AttachmentSlots.Blade_WeaponMod1");
        ArrayPush(slots, t"AttachmentSlots.Blade_WeaponMod2");
        ArrayPush(slots, t"AttachmentSlots.Blade_WeaponMod3");
        ArrayPush(slots, t"AttachmentSlots.Blade_WeaponMod4");
        ArrayPush(slots, t"AttachmentSlots.Blade_WeaponMod5");
        ArrayPush(slots, t"AttachmentSlots.Blade_WeaponMod6");
        ArrayPush(slots, t"AttachmentSlots.Blade_WeaponMod1_Collectible");
        ArrayPush(slots, t"AttachmentSlots.Blade_WeaponMod2_Collectible");
        ArrayPush(slots, t"AttachmentSlots.Blunt_WeaponMod1");
        ArrayPush(slots, t"AttachmentSlots.Blunt_WeaponMod2");
        ArrayPush(slots, t"AttachmentSlots.Blunt_WeaponMod3");
        ArrayPush(slots, t"AttachmentSlots.Blunt_WeaponMod4");
        ArrayPush(slots, t"AttachmentSlots.Blunt_WeaponMod5");
        ArrayPush(slots, t"AttachmentSlots.Blunt_WeaponMod6");
        ArrayPush(slots, t"AttachmentSlots.Blunt_WeaponMod1_Collectible");
        ArrayPush(slots, t"AttachmentSlots.Blunt_WeaponMod2_Collectible");
        ArrayPush(slots, t"AttachmentSlots.Throwable_WeaponMod1");
        ArrayPush(slots, t"AttachmentSlots.Throwable_WeaponMod2");
        ArrayPush(slots, t"AttachmentSlots.Throwable_WeaponMod3");
        ArrayPush(slots, t"AttachmentSlots.Throwable_WeaponMod4");
        ArrayPush(slots, t"AttachmentSlots.Throwable_WeaponMod5");
        ArrayPush(slots, t"AttachmentSlots.Throwable_WeaponMod6");
        ArrayPush(slots, t"AttachmentSlots.Throwable_WeaponMod1_Collectible");
        ArrayPush(slots, t"AttachmentSlots.Throwable_WeaponMod2_Collectible");
        ArrayPush(slots, t"AttachmentSlots.IconicMeleeWeaponMod1");
        break;
      default:
        ArrayPush(slots, t"AttachmentSlots.KiroshiOpticsSlot1");
        ArrayPush(slots, t"AttachmentSlots.KiroshiOpticsSlot2");
        ArrayPush(slots, t"AttachmentSlots.KiroshiOpticsSlot3");
        ArrayPush(slots, t"AttachmentSlots.SandevistanSlot1");
        ArrayPush(slots, t"AttachmentSlots.SandevistanSlot2");
        ArrayPush(slots, t"AttachmentSlots.SandevistanSlot3");
        ArrayPush(slots, t"AttachmentSlots.CyberdeckProgram1");
        ArrayPush(slots, t"AttachmentSlots.CyberdeckProgram2");
        ArrayPush(slots, t"AttachmentSlots.CyberdeckProgram3");
        ArrayPush(slots, t"AttachmentSlots.CyberdeckProgram4");
        ArrayPush(slots, t"AttachmentSlots.CyberdeckProgram5");
        ArrayPush(slots, t"AttachmentSlots.CyberdeckProgram6");
        ArrayPush(slots, t"AttachmentSlots.CyberdeckProgram7");
        ArrayPush(slots, t"AttachmentSlots.CyberdeckProgram8");
		ArrayPush(slots, t"AttachmentSlots.CyberdeckProgram9");
		ArrayPush(slots, t"AttachmentSlots.CyberdeckProgram10");
		ArrayPush(slots, t"AttachmentSlots.CyberdeckProgram11");
		ArrayPush(slots, t"AttachmentSlots.CyberdeckProgram12");
		ArrayPush(slots, t"AttachmentSlots.CyberdeckProgram13");
		ArrayPush(slots, t"AttachmentSlots.CyberdeckProgram14");
		ArrayPush(slots, t"AttachmentSlots.CyberdeckProgram15");
		ArrayPush(slots, t"AttachmentSlots.CyberdeckProgram16");
        ArrayPush(slots, t"AttachmentSlots.BerserkSlot1");
        ArrayPush(slots, t"AttachmentSlots.BerserkSlot2");
        ArrayPush(slots, t"AttachmentSlots.BerserkSlot3");
        ArrayPush(slots, t"AttachmentSlots.NanoWiresQuickhackSlot");
        ArrayPush(slots, t"AttachmentSlots.NanoWiresQuickhackSlot1");
    };
    return slots;
  }


@replaceMethod(InventoryDataManagerV2)
  public final static func GetAttachmentSlotsForInventory() -> [TweakDBID] {
    let slots: array<TweakDBID>;
    ArrayPush(slots, t"AttachmentSlots.Scope");
    ArrayPush(slots, t"AttachmentSlots.PowerModule");
    ArrayPush(slots, t"AttachmentSlots.Gem");
    ArrayPush(slots, t"AttachmentSlots.CyberdeckProgram1");
    ArrayPush(slots, t"AttachmentSlots.CyberdeckProgram2");
    ArrayPush(slots, t"AttachmentSlots.CyberdeckProgram3");
    ArrayPush(slots, t"AttachmentSlots.CyberdeckProgram4");
    ArrayPush(slots, t"AttachmentSlots.CyberdeckProgram5");
    ArrayPush(slots, t"AttachmentSlots.CyberdeckProgram6");
    ArrayPush(slots, t"AttachmentSlots.CyberdeckProgram7");
    ArrayPush(slots, t"AttachmentSlots.CyberdeckProgram8");
    ArrayPush(slots, t"AttachmentSlots.CyberdeckProgram9");
    ArrayPush(slots, t"AttachmentSlots.CyberdeckProgram10");
    ArrayPush(slots, t"AttachmentSlots.CyberdeckProgram11");
    ArrayPush(slots, t"AttachmentSlots.CyberdeckProgram12");
    ArrayPush(slots, t"AttachmentSlots.CyberdeckProgram13");
    ArrayPush(slots, t"AttachmentSlots.CyberdeckProgram14");
    ArrayPush(slots, t"AttachmentSlots.CyberdeckProgram15");
    ArrayPush(slots, t"AttachmentSlots.CyberdeckProgram16");
    ArrayPush(slots, t"AttachmentSlots.HeadFabricEnhancer1");
    ArrayPush(slots, t"AttachmentSlots.HeadFabricEnhancer2");
    ArrayPush(slots, t"AttachmentSlots.HeadFabricEnhancer3");
    ArrayPush(slots, t"AttachmentSlots.FaceFabricEnhancer1");
    ArrayPush(slots, t"AttachmentSlots.FaceFabricEnhancer2");
    ArrayPush(slots, t"AttachmentSlots.FaceFabricEnhancer3");
    ArrayPush(slots, t"AttachmentSlots.KiroshiOpticsSlot1");
    ArrayPush(slots, t"AttachmentSlots.KiroshiOpticsSlot2");
    ArrayPush(slots, t"AttachmentSlots.KiroshiOpticsSlot3");
    ArrayPush(slots, t"AttachmentSlots.SandevistanSlot1");
    ArrayPush(slots, t"AttachmentSlots.SandevistanSlot2");
    ArrayPush(slots, t"AttachmentSlots.SandevistanSlot3");
    ArrayPush(slots, t"AttachmentSlots.BerserkSlot1");
    ArrayPush(slots, t"AttachmentSlots.BerserkSlot2");
    ArrayPush(slots, t"AttachmentSlots.BerserkSlot3");
    ArrayPush(slots, t"AttachmentSlots.InnerChestFabricEnhancer1");
    ArrayPush(slots, t"AttachmentSlots.InnerChestFabricEnhancer2");
    ArrayPush(slots, t"AttachmentSlots.InnerChestFabricEnhancer3");
    ArrayPush(slots, t"AttachmentSlots.InnerChestFabricEnhancer4");
    ArrayPush(slots, t"AttachmentSlots.OuterChestFabricEnhancer1");
    ArrayPush(slots, t"AttachmentSlots.OuterChestFabricEnhancer2");
    ArrayPush(slots, t"AttachmentSlots.OuterChestFabricEnhancer3");
    ArrayPush(slots, t"AttachmentSlots.OuterChestFabricEnhancer4");
    ArrayPush(slots, t"AttachmentSlots.LegsFabricEnhancer1");
    ArrayPush(slots, t"AttachmentSlots.LegsFabricEnhancer2");
    ArrayPush(slots, t"AttachmentSlots.LegsFabricEnhancer3");
    ArrayPush(slots, t"AttachmentSlots.FootFabricEnhancer1");
    ArrayPush(slots, t"AttachmentSlots.FootFabricEnhancer2");
    ArrayPush(slots, t"AttachmentSlots.FootFabricEnhancer3");
    ArrayPush(slots, t"AttachmentSlots.NanoWiresQuickhackSlot");
    ArrayPush(slots, t"AttachmentSlots.NanoWiresQuickhackSlot1");
    ArrayPush(slots, t"AttachmentSlots.Power_AR_SMG_LMG_WeaponMod1");
    ArrayPush(slots, t"AttachmentSlots.Power_AR_SMG_LMG_WeaponMod2");
    ArrayPush(slots, t"AttachmentSlots.Power_AR_SMG_LMG_WeaponMod1_Collectible");
    ArrayPush(slots, t"AttachmentSlots.Power_AR_SMG_LMG_WeaponMod2_Collectible");
    ArrayPush(slots, t"AttachmentSlots.Tech_AR_SMG_LMG_WeaponMod1");
    ArrayPush(slots, t"AttachmentSlots.Tech_AR_SMG_LMG_WeaponMod2");
    ArrayPush(slots, t"AttachmentSlots.Smart_AR_SMG_LMG_WeaponMod1");
    ArrayPush(slots, t"AttachmentSlots.Smart_AR_SMG_LMG_WeaponMod2");
    ArrayPush(slots, t"AttachmentSlots.Power_AR_SMG_LMG_WeaponMod3");
    ArrayPush(slots, t"AttachmentSlots.Power_AR_SMG_LMG_WeaponMod4");
    ArrayPush(slots, t"AttachmentSlots.Power_AR_SMG_LMG_WeaponMod5");
    ArrayPush(slots, t"AttachmentSlots.Power_AR_SMG_LMG_WeaponMod6");
    ArrayPush(slots, t"AttachmentSlots.Tech_AR_SMG_LMG_WeaponMod3");
    ArrayPush(slots, t"AttachmentSlots.Tech_AR_SMG_LMG_WeaponMod4");
    ArrayPush(slots, t"AttachmentSlots.Tech_AR_SMG_LMG_WeaponMod5");
    ArrayPush(slots, t"AttachmentSlots.Tech_AR_SMG_LMG_WeaponMod6");
    ArrayPush(slots, t"AttachmentSlots.Smart_AR_SMG_LMG_WeaponMod3");
    ArrayPush(slots, t"AttachmentSlots.Smart_AR_SMG_LMG_WeaponMod4");
    ArrayPush(slots, t"AttachmentSlots.Smart_AR_SMG_LMG_WeaponMod5");
    ArrayPush(slots, t"AttachmentSlots.Smart_AR_SMG_LMG_WeaponMod6");
    ArrayPush(slots, t"AttachmentSlots.Power_Precision_Sniper_Rifle_WeaponMod3");
    ArrayPush(slots, t"AttachmentSlots.Power_Precision_Sniper_Rifle_WeaponMod4");
    ArrayPush(slots, t"AttachmentSlots.Power_Precision_Sniper_Rifle_WeaponMod5");
    ArrayPush(slots, t"AttachmentSlots.Power_Precision_Sniper_Rifle_WeaponMod6");
    ArrayPush(slots, t"AttachmentSlots.Tech_Precision_Sniper_Rifle_WeaponMod3");
    ArrayPush(slots, t"AttachmentSlots.Tech_Precision_Sniper_Rifle_WeaponMod4");
    ArrayPush(slots, t"AttachmentSlots.Tech_Precision_Sniper_Rifle_WeaponMod5");
    ArrayPush(slots, t"AttachmentSlots.Tech_Precision_Sniper_Rifle_WeaponMod6");
    ArrayPush(slots, t"AttachmentSlots.Smart_Precision_Sniper_Rifle_WeaponMod3");
    ArrayPush(slots, t"AttachmentSlots.Smart_Precision_Sniper_Rifle_WeaponMod4");
    ArrayPush(slots, t"AttachmentSlots.Smart_Precision_Sniper_Rifle_WeaponMod5");
    ArrayPush(slots, t"AttachmentSlots.Smart_Precision_Sniper_Rifle_WeaponMod6");
    ArrayPush(slots, t"AttachmentSlots.Power_Shotgun_WeaponMod3");
    ArrayPush(slots, t"AttachmentSlots.Power_Shotgun_WeaponMod4");
    ArrayPush(slots, t"AttachmentSlots.Power_Shotgun_WeaponMod5");
    ArrayPush(slots, t"AttachmentSlots.Power_Shotgun_WeaponMod6");
    ArrayPush(slots, t"AttachmentSlots.Tech_Shotgun_WeaponMod3");
    ArrayPush(slots, t"AttachmentSlots.Tech_Shotgun_WeaponMod4");
    ArrayPush(slots, t"AttachmentSlots.Tech_Shotgun_WeaponMod5");
    ArrayPush(slots, t"AttachmentSlots.Tech_Shotgun_WeaponMod6");
    ArrayPush(slots, t"AttachmentSlots.Smart_Shotgun_WeaponMod3");
    ArrayPush(slots, t"AttachmentSlots.Smart_Shotgun_WeaponMod4");
    ArrayPush(slots, t"AttachmentSlots.Smart_Shotgun_WeaponMod5");
    ArrayPush(slots, t"AttachmentSlots.Smart_Shotgun_WeaponMod6");
    ArrayPush(slots, t"AttachmentSlots.Power_Handgun_WeaponMod1");
    ArrayPush(slots, t"AttachmentSlots.Power_Handgun_WeaponMod2");
    ArrayPush(slots, t"AttachmentSlots.Power_Handgun_WeaponMod3");
    ArrayPush(slots, t"AttachmentSlots.Power_Handgun_WeaponMod4");
    ArrayPush(slots, t"AttachmentSlots.Power_Handgun_WeaponMod5");
    ArrayPush(slots, t"AttachmentSlots.Power_Handgun_WeaponMod6");
    ArrayPush(slots, t"AttachmentSlots.Smart_Handgun_WeaponMod3");
    ArrayPush(slots, t"AttachmentSlots.Smart_Handgun_WeaponMod4");
    ArrayPush(slots, t"AttachmentSlots.Smart_Handgun_WeaponMod5");
    ArrayPush(slots, t"AttachmentSlots.Smart_Handgun_WeaponMod6");
    ArrayPush(slots, t"AttachmentSlots.Tech_Handgun_WeaponMod3");
    ArrayPush(slots, t"AttachmentSlots.Tech_Handgun_WeaponMod4");
    ArrayPush(slots, t"AttachmentSlots.Tech_Handgun_WeaponMod5");
    ArrayPush(slots, t"AttachmentSlots.Tech_Handgun_WeaponMod6");
    ArrayPush(slots, t"AttachmentSlots.Power_Handgun_WeaponMod1_Collectible");
    ArrayPush(slots, t"AttachmentSlots.Power_Handgun_WeaponMod2_Collectible");
    ArrayPush(slots, t"AttachmentSlots.Tech_Handgun_WeaponMod1");
    ArrayPush(slots, t"AttachmentSlots.Tech_Handgun_WeaponMod2");
    ArrayPush(slots, t"AttachmentSlots.Smart_Handgun_WeaponMod1");
    ArrayPush(slots, t"AttachmentSlots.Smart_Handgun_WeaponMod2");
    ArrayPush(slots, t"AttachmentSlots.Smart_Handgun_WeaponMod1_Collectible");
    ArrayPush(slots, t"AttachmentSlots.Smart_Handgun_WeaponMod2_Collectible");
    ArrayPush(slots, t"AttachmentSlots.Power_Precision_Sniper_Rifle_WeaponMod1");
    ArrayPush(slots, t"AttachmentSlots.Power_Precision_Sniper_Rifle_WeaponMod2");
    ArrayPush(slots, t"AttachmentSlots.Tech_Precision_Sniper_Rifle_WeaponMod1");
    ArrayPush(slots, t"AttachmentSlots.Tech_Precision_Sniper_Rifle_WeaponMod2");
    ArrayPush(slots, t"AttachmentSlots.Tech_Precision_Sniper_Rifle_WeaponMod1_Collectible");
    ArrayPush(slots, t"AttachmentSlots.Tech_Precision_Sniper_Rifle_WeaponMod2_Collectible");
    ArrayPush(slots, t"AttachmentSlots.Smart_Precision_Sniper_Rifle_WeaponMod1");
    ArrayPush(slots, t"AttachmentSlots.Smart_Precision_Sniper_Rifle_WeaponMod2");
    ArrayPush(slots, t"AttachmentSlots.Smart_Precision_Sniper_Rifle_WeaponMod1_Collectible");
    ArrayPush(slots, t"AttachmentSlots.Smart_Precision_Sniper_Rifle_WeaponMod2_Collectible");
    ArrayPush(slots, t"AttachmentSlots.Power_Shotgun_WeaponMod1");
    ArrayPush(slots, t"AttachmentSlots.Power_Shotgun_WeaponMod2");
    ArrayPush(slots, t"AttachmentSlots.Power_Shotgun_WeaponMod1_Collectible");
    ArrayPush(slots, t"AttachmentSlots.Power_Shotgun_WeaponMod2_Collectible");
    ArrayPush(slots, t"AttachmentSlots.Tech_Shotgun_WeaponMod1");
    ArrayPush(slots, t"AttachmentSlots.Tech_Shotgun_WeaponMod2");
    ArrayPush(slots, t"AttachmentSlots.Smart_Shotgun_WeaponMod1");
    ArrayPush(slots, t"AttachmentSlots.Smart_Shotgun_WeaponMod2");
    ArrayPush(slots, t"AttachmentSlots.IconicWeaponModLegendary");
    ArrayPush(slots, t"AttachmentSlots.Blade_WeaponMod1");
    ArrayPush(slots, t"AttachmentSlots.Blade_WeaponMod2");
    ArrayPush(slots, t"AttachmentSlots.Blade_WeaponMod3");
    ArrayPush(slots, t"AttachmentSlots.Blade_WeaponMod4");
    ArrayPush(slots, t"AttachmentSlots.Blade_WeaponMod5");
    ArrayPush(slots, t"AttachmentSlots.Blade_WeaponMod6");
    ArrayPush(slots, t"AttachmentSlots.Blade_WeaponMod1_Collectible");
    ArrayPush(slots, t"AttachmentSlots.Blade_WeaponMod2_Collectible");
    ArrayPush(slots, t"AttachmentSlots.Blunt_WeaponMod1");
    ArrayPush(slots, t"AttachmentSlots.Blunt_WeaponMod2");
    ArrayPush(slots, t"AttachmentSlots.Blunt_WeaponMod3");
    ArrayPush(slots, t"AttachmentSlots.Blunt_WeaponMod4");
    ArrayPush(slots, t"AttachmentSlots.Blunt_WeaponMod5");
    ArrayPush(slots, t"AttachmentSlots.Blunt_WeaponMod6");
    ArrayPush(slots, t"AttachmentSlots.Blunt_WeaponMod1_Collectible");
    ArrayPush(slots, t"AttachmentSlots.Blunt_WeaponMod2_Collectible");
    ArrayPush(slots, t"AttachmentSlots.Throwable_WeaponMod1");
    ArrayPush(slots, t"AttachmentSlots.Throwable_WeaponMod2");
    ArrayPush(slots, t"AttachmentSlots.Throwable_WeaponMod3");
    ArrayPush(slots, t"AttachmentSlots.Throwable_WeaponMod4");
    ArrayPush(slots, t"AttachmentSlots.Throwable_WeaponMod5");
    ArrayPush(slots, t"AttachmentSlots.Throwable_WeaponMod6");
    ArrayPush(slots, t"AttachmentSlots.Throwable_WeaponMod1_Collectible");
    ArrayPush(slots, t"AttachmentSlots.Throwable_WeaponMod2_Collectible");
    ArrayPush(slots, t"AttachmentSlots.IconicMeleeWeaponMod1");
    return slots;
  }

@replaceMethod(UIItemsHelper)
  public final static func GetSlotShadowIcon(slotID: TweakDBID, itemType: gamedataItemType, equipmentArea: gamedataEquipmentArea) -> CName {
    switch slotID {
      case t"AttachmentSlots.Scope":
        return n"UIIcon.ItemShadow_Scope";
      case t"AttachmentSlots.PowerModule":
        return n"UIIcon.ItemShadow_Silencer";
      case t"AttachmentSlots.Magazine":
        return n"UIIcon.ItemShadow_Magazine";
      case t"AttachmentSlots.Throwable_WeaponMod2_Collectible":
      case t"AttachmentSlots.Throwable_WeaponMod1_Collectible":
      case t"AttachmentSlots.Throwable_WeaponMod6":
      case t"AttachmentSlots.Throwable_WeaponMod5":
      case t"AttachmentSlots.Throwable_WeaponMod4":
      case t"AttachmentSlots.Throwable_WeaponMod3":
      case t"AttachmentSlots.Throwable_WeaponMod2":
      case t"AttachmentSlots.Throwable_WeaponMod1":
      case t"AttachmentSlots.Blunt_WeaponMod2_Collectible":
      case t"AttachmentSlots.Blunt_WeaponMod1_Collectible":
      case t"AttachmentSlots.Blunt_WeaponMod6":
      case t"AttachmentSlots.Blunt_WeaponMod5":
      case t"AttachmentSlots.Blunt_WeaponMod4":
      case t"AttachmentSlots.Blunt_WeaponMod3":
      case t"AttachmentSlots.Blunt_WeaponMod2":
      case t"AttachmentSlots.Blunt_WeaponMod1":
      case t"AttachmentSlots.Blade_WeaponMod2_Collectible":
      case t"AttachmentSlots.Blade_WeaponMod1_Collectible":
      case t"AttachmentSlots.Blade_WeaponMod6":
      case t"AttachmentSlots.Blade_WeaponMod5":
      case t"AttachmentSlots.Blade_WeaponMod4":
      case t"AttachmentSlots.Blade_WeaponMod3":
      case t"AttachmentSlots.Blade_WeaponMod2":
      case t"AttachmentSlots.Blade_WeaponMod1":
      case t"AttachmentSlots.Smart_Precision_Sniper_Rifle_WeaponMod2_Collectible":
      case t"AttachmentSlots.Smart_Precision_Sniper_Rifle_WeaponMod1_Collectible":
      case t"AttachmentSlots.Smart_Precision_Sniper_Rifle_WeaponMod2":
      case t"AttachmentSlots.Smart_Precision_Sniper_Rifle_WeaponMod1":
      case t"AttachmentSlots.Tech_Precision_Sniper_Rifle_WeaponMod2_Collectible":
      case t"AttachmentSlots.Tech_Precision_Sniper_Rifle_WeaponMod1_Collectible":
      case t"AttachmentSlots.Tech_Precision_Sniper_Rifle_WeaponMod2":
      case t"AttachmentSlots.Tech_Precision_Sniper_Rifle_WeaponMod1":
      case t"AttachmentSlots.Power_Precision_Sniper_Rifle_WeaponMod2":
      case t"AttachmentSlots.Power_Precision_Sniper_Rifle_WeaponMod1":
      case t"AttachmentSlots.Smart_Precision_Sniper_Rifle_WeaponMod6":
      case t"AttachmentSlots.Smart_Precision_Sniper_Rifle_WeaponMod5":
      case t"AttachmentSlots.Smart_Precision_Sniper_Rifle_WeaponMod4":
      case t"AttachmentSlots.Smart_Precision_Sniper_Rifle_WeaponMod3":
      case t"AttachmentSlots.Tech_Precision_Sniper_Rifle_WeaponMod6":
      case t"AttachmentSlots.Tech_Precision_Sniper_Rifle_WeaponMod5":
      case t"AttachmentSlots.Tech_Precision_Sniper_Rifle_WeaponMod4":
      case t"AttachmentSlots.Tech_Precision_Sniper_Rifle_WeaponMod3":
      case t"AttachmentSlots.Power_Precision_Sniper_Rifle_WeaponMod6":
      case t"AttachmentSlots.Power_Precision_Sniper_Rifle_WeaponMod5":
      case t"AttachmentSlots.Power_Precision_Sniper_Rifle_WeaponMod4":
      case t"AttachmentSlots.Power_Precision_Sniper_Rifle_WeaponMod3":
      case t"AttachmentSlots.Smart_Shotgun_WeaponMod6":
      case t"AttachmentSlots.Smart_Shotgun_WeaponMod5":
      case t"AttachmentSlots.Smart_Shotgun_WeaponMod4":
      case t"AttachmentSlots.Smart_Shotgun_WeaponMod3":
      case t"AttachmentSlots.Tech_Shotgun_WeaponMod6":
      case t"AttachmentSlots.Tech_Shotgun_WeaponMod5":
      case t"AttachmentSlots.Tech_Shotgun_WeaponMod4":
      case t"AttachmentSlots.Tech_Shotgun_WeaponMod3":
      case t"AttachmentSlots.Power_Shotgun_WeaponMod6":
      case t"AttachmentSlots.Power_Shotgun_WeaponMod5":
      case t"AttachmentSlots.Power_Shotgun_WeaponMod4":
      case t"AttachmentSlots.Power_Shotgun_WeaponMod3":
      case t"AttachmentSlots.Smart_AR_SMG_LMG_WeaponMod6":
      case t"AttachmentSlots.Smart_AR_SMG_LMG_WeaponMod5":
      case t"AttachmentSlots.Smart_AR_SMG_LMG_WeaponMod4":
      case t"AttachmentSlots.Smart_AR_SMG_LMG_WeaponMod3":
      case t"AttachmentSlots.Tech_AR_SMG_LMG_WeaponMod6":
      case t"AttachmentSlots.Tech_AR_SMG_LMG_WeaponMod5":
      case t"AttachmentSlots.Tech_AR_SMG_LMG_WeaponMod4":
      case t"AttachmentSlots.Tech_AR_SMG_LMG_WeaponMod3":
      case t"AttachmentSlots.Power_AR_SMG_LMG_WeaponMod6":
      case t"AttachmentSlots.Power_AR_SMG_LMG_WeaponMod5":
      case t"AttachmentSlots.Power_AR_SMG_LMG_WeaponMod4":
      case t"AttachmentSlots.Power_AR_SMG_LMG_WeaponMod3":
      case t"AttachmentSlots.Smart_Shotgun_WeaponMod2":
      case t"AttachmentSlots.Smart_Shotgun_WeaponMod1":
      case t"AttachmentSlots.Tech_Shotgun_WeaponMod2":
      case t"AttachmentSlots.Tech_Shotgun_WeaponMod1":
      case t"AttachmentSlots.Power_Shotgun_WeaponMod2_Collectible":
      case t"AttachmentSlots.Power_Shotgun_WeaponMod1_Collectible":
      case t"AttachmentSlots.Power_Shotgun_WeaponMod2":
      case t"AttachmentSlots.Power_Shotgun_WeaponMod1":
      case t"AttachmentSlots.Smart_Handgun_WeaponMod2_Collectible":
      case t"AttachmentSlots.Smart_Handgun_WeaponMod1_Collectible":
      case t"AttachmentSlots.Smart_Handgun_WeaponMod2":
      case t"AttachmentSlots.Smart_Handgun_WeaponMod1":
      case t"AttachmentSlots.Tech_Handgun_WeaponMod2":
      case t"AttachmentSlots.Tech_Handgun_WeaponMod1":
      case t"AttachmentSlots.Power_Handgun_WeaponMod2_Collectible":
      case t"AttachmentSlots.Power_Handgun_WeaponMod1_Collectible":
      case t"AttachmentSlots.Power_Handgun_WeaponMod2":
      case t"AttachmentSlots.Power_Handgun_WeaponMod1":
      case t"AttachmentSlots.Power_Handgun_WeaponMod6":
      case t"AttachmentSlots.Power_Handgun_WeaponMod5":
      case t"AttachmentSlots.Power_Handgun_WeaponMod4":
      case t"AttachmentSlots.Power_Handgun_WeaponMod3":
      case t"AttachmentSlots.Smart_Handgun_WeaponMod6":
      case t"AttachmentSlots.Smart_Handgun_WeaponMod5":
      case t"AttachmentSlots.Smart_Handgun_WeaponMod4":
      case t"AttachmentSlots.Smart_Handgun_WeaponMod3":
      case t"AttachmentSlots.Tech_Handgun_WeaponMod6":
      case t"AttachmentSlots.Tech_Handgun_WeaponMod5":
      case t"AttachmentSlots.Tech_Handgun_WeaponMod4":
      case t"AttachmentSlots.Tech_Handgun_WeaponMod3":
      case t"AttachmentSlots.Smart_AR_SMG_LMG_WeaponMod2":
      case t"AttachmentSlots.Smart_AR_SMG_LMG_WeaponMod1":
      case t"AttachmentSlots.Tech_AR_SMG_LMG_WeaponMod2":
      case t"AttachmentSlots.Tech_AR_SMG_LMG_WeaponMod1":
      case t"AttachmentSlots.Power_AR_SMG_LMG_WeaponMod2_Collectible":
      case t"AttachmentSlots.Power_AR_SMG_LMG_WeaponMod1_Collectible":
      case t"AttachmentSlots.Power_AR_SMG_LMG_WeaponMod2":
      case t"AttachmentSlots.Power_AR_SMG_LMG_WeaponMod1":
        return n"UIIcon.ItemShadow_Mod";
      case t"AttachmentSlots.NanoWiresQuickhackSlot":
      case t"AttachmentSlots.NanoWiresQuickhackSlot1":
      case t"AttachmentSlots.CyberdeckProgram16":
      case t"AttachmentSlots.CyberdeckProgram15":
      case t"AttachmentSlots.CyberdeckProgram14":
      case t"AttachmentSlots.CyberdeckProgram13":
      case t"AttachmentSlots.CyberdeckProgram12":
      case t"AttachmentSlots.CyberdeckProgram11":
      case t"AttachmentSlots.CyberdeckProgram10":
      case t"AttachmentSlots.CyberdeckProgram9":
      case t"AttachmentSlots.CyberdeckProgram8":
      case t"AttachmentSlots.CyberdeckProgram7":
      case t"AttachmentSlots.CyberdeckProgram6":
      case t"AttachmentSlots.CyberdeckProgram5":
      case t"AttachmentSlots.CyberdeckProgram4":
      case t"AttachmentSlots.CyberdeckProgram3":
      case t"AttachmentSlots.CyberdeckProgram2":
      case t"AttachmentSlots.CyberdeckProgram1":
        return n"UIIcon.ItemShadow_Program";
      case t"AttachmentSlots.ArmsCyberwareGeneralSlot":
      case t"AttachmentSlots.ProjectileLauncherWiring":
      case t"AttachmentSlots.ProjectileLauncherRound":
      case t"AttachmentSlots.NanoWiresBattery":
      case t"AttachmentSlots.NanoWiresCable":
      case t"AttachmentSlots.MantisBladesRotor":
      case t"AttachmentSlots.MantisBladesEdge":
      case t"AttachmentSlots.StrongArmsBattery":
      case t"AttachmentSlots.StrongArmsKnuckles":
      case t"AttachmentSlots.KiroshiOpticsSlot3":
      case t"AttachmentSlots.KiroshiOpticsSlot2":
      case t"AttachmentSlots.KiroshiOpticsSlot1":
      case t"AttachmentSlots.BerserkSlot3":
      case t"AttachmentSlots.BerserkSlot2":
      case t"AttachmentSlots.BerserkSlot1":
      case t"AttachmentSlots.SandevistanSlot3":
      case t"AttachmentSlots.SandevistanSlot2":
      case t"AttachmentSlots.SandevistanSlot1":
        return n"UIIcon.ItemShadow_Fragment";
      case t"AttachmentSlots.FootFabricEnhancer3":
      case t"AttachmentSlots.FootFabricEnhancer2":
      case t"AttachmentSlots.FootFabricEnhancer1":
      case t"AttachmentSlots.LegsFabricEnhancer3":
      case t"AttachmentSlots.LegsFabricEnhancer2":
      case t"AttachmentSlots.LegsFabricEnhancer1":
      case t"AttachmentSlots.OuterChestFabricEnhancer3":
      case t"AttachmentSlots.OuterChestFabricEnhancer2":
      case t"AttachmentSlots.OuterChestFabricEnhancer1":
      case t"AttachmentSlots.InnerChestFabricEnhancer3":
      case t"AttachmentSlots.InnerChestFabricEnhancer2":
      case t"AttachmentSlots.InnerChestFabricEnhancer1":
      case t"AttachmentSlots.FaceFabricEnhancer3":
      case t"AttachmentSlots.FaceFabricEnhancer2":
      case t"AttachmentSlots.FaceFabricEnhancer1":
      case t"AttachmentSlots.HeadFabricEnhancer3":
      case t"AttachmentSlots.HeadFabricEnhancer2":
      case t"AttachmentSlots.HeadFabricEnhancer1":
        return n"UIIcon.ItemShadow_Material";
    };
    return UIItemsHelper.GetSlotShadowIcon(itemType, equipmentArea);
  }


@replaceMethod(UIItemsHelper)
  public final static func GetLootingShadowIcon(slotID: TweakDBID, itemType: gamedataItemType, equipmentArea: gamedataEquipmentArea) -> CName {
    switch slotID {
      case t"AttachmentSlots.Scope":
        return n"UIIcon.LootingShadow_Scope";
      case t"AttachmentSlots.PowerModule":
        return n"UIIcon.LootingShadow_Silencer";
      case t"AttachmentSlots.Magazine":
        return n"UIIcon.LootingShadow_Magazine";
      case t"AttachmentSlots.Throwable_WeaponMod2_Collectible":
      case t"AttachmentSlots.Throwable_WeaponMod1_Collectible":
      case t"AttachmentSlots.Throwable_WeaponMod6":
      case t"AttachmentSlots.Throwable_WeaponMod5":
      case t"AttachmentSlots.Throwable_WeaponMod4":
      case t"AttachmentSlots.Throwable_WeaponMod3":
      case t"AttachmentSlots.Throwable_WeaponMod2":
      case t"AttachmentSlots.Throwable_WeaponMod1":
      case t"AttachmentSlots.Blunt_WeaponMod2_Collectible":
      case t"AttachmentSlots.Blunt_WeaponMod1_Collectible":
      case t"AttachmentSlots.Blunt_WeaponMod6":
      case t"AttachmentSlots.Blunt_WeaponMod5":
      case t"AttachmentSlots.Blunt_WeaponMod4":
      case t"AttachmentSlots.Blunt_WeaponMod3":
      case t"AttachmentSlots.Blunt_WeaponMod2":
      case t"AttachmentSlots.Blunt_WeaponMod1":
      case t"AttachmentSlots.Blade_WeaponMod2_Collectible":
      case t"AttachmentSlots.Blade_WeaponMod1_Collectible":
      case t"AttachmentSlots.Blade_WeaponMod6":
      case t"AttachmentSlots.Blade_WeaponMod5":
      case t"AttachmentSlots.Blade_WeaponMod4":
      case t"AttachmentSlots.Blade_WeaponMod3":
      case t"AttachmentSlots.Blade_WeaponMod2":
      case t"AttachmentSlots.Blade_WeaponMod1":
      case t"AttachmentSlots.Smart_Precision_Sniper_Rifle_WeaponMod2_Collectible":
      case t"AttachmentSlots.Smart_Precision_Sniper_Rifle_WeaponMod1_Collectible":
      case t"AttachmentSlots.Smart_Precision_Sniper_Rifle_WeaponMod2":
      case t"AttachmentSlots.Smart_Precision_Sniper_Rifle_WeaponMod1":
      case t"AttachmentSlots.Tech_Precision_Sniper_Rifle_WeaponMod2_Collectible":
      case t"AttachmentSlots.Tech_Precision_Sniper_Rifle_WeaponMod1_Collectible":
      case t"AttachmentSlots.Tech_Precision_Sniper_Rifle_WeaponMod2":
      case t"AttachmentSlots.Tech_Precision_Sniper_Rifle_WeaponMod1":
      case t"AttachmentSlots.Power_Precision_Sniper_Rifle_WeaponMod2":
      case t"AttachmentSlots.Power_Precision_Sniper_Rifle_WeaponMod1":
      case t"AttachmentSlots.Smart_Precision_Sniper_Rifle_WeaponMod6":
      case t"AttachmentSlots.Smart_Precision_Sniper_Rifle_WeaponMod5":
      case t"AttachmentSlots.Smart_Precision_Sniper_Rifle_WeaponMod4":
      case t"AttachmentSlots.Smart_Precision_Sniper_Rifle_WeaponMod3":
      case t"AttachmentSlots.Tech_Precision_Sniper_Rifle_WeaponMod6":
      case t"AttachmentSlots.Tech_Precision_Sniper_Rifle_WeaponMod5":
      case t"AttachmentSlots.Tech_Precision_Sniper_Rifle_WeaponMod4":
      case t"AttachmentSlots.Tech_Precision_Sniper_Rifle_WeaponMod3":
      case t"AttachmentSlots.Power_Precision_Sniper_Rifle_WeaponMod6":
      case t"AttachmentSlots.Power_Precision_Sniper_Rifle_WeaponMod5":
      case t"AttachmentSlots.Power_Precision_Sniper_Rifle_WeaponMod4":
      case t"AttachmentSlots.Power_Precision_Sniper_Rifle_WeaponMod3":
      case t"AttachmentSlots.Smart_Shotgun_WeaponMod6":
      case t"AttachmentSlots.Smart_Shotgun_WeaponMod5":
      case t"AttachmentSlots.Smart_Shotgun_WeaponMod4":
      case t"AttachmentSlots.Smart_Shotgun_WeaponMod3":
      case t"AttachmentSlots.Tech_Shotgun_WeaponMod6":
      case t"AttachmentSlots.Tech_Shotgun_WeaponMod5":
      case t"AttachmentSlots.Tech_Shotgun_WeaponMod4":
      case t"AttachmentSlots.Tech_Shotgun_WeaponMod3":
      case t"AttachmentSlots.Power_Shotgun_WeaponMod6":
      case t"AttachmentSlots.Power_Shotgun_WeaponMod5":
      case t"AttachmentSlots.Power_Shotgun_WeaponMod4":
      case t"AttachmentSlots.Power_Shotgun_WeaponMod3":
      case t"AttachmentSlots.Smart_AR_SMG_LMG_WeaponMod6":
      case t"AttachmentSlots.Smart_AR_SMG_LMG_WeaponMod5":
      case t"AttachmentSlots.Smart_AR_SMG_LMG_WeaponMod4":
      case t"AttachmentSlots.Smart_AR_SMG_LMG_WeaponMod3":
      case t"AttachmentSlots.Tech_AR_SMG_LMG_WeaponMod6":
      case t"AttachmentSlots.Tech_AR_SMG_LMG_WeaponMod5":
      case t"AttachmentSlots.Tech_AR_SMG_LMG_WeaponMod4":
      case t"AttachmentSlots.Tech_AR_SMG_LMG_WeaponMod3":
      case t"AttachmentSlots.Power_AR_SMG_LMG_WeaponMod6":
      case t"AttachmentSlots.Power_AR_SMG_LMG_WeaponMod5":
      case t"AttachmentSlots.Power_AR_SMG_LMG_WeaponMod4":
      case t"AttachmentSlots.Power_AR_SMG_LMG_WeaponMod3":
      case t"AttachmentSlots.Smart_Shotgun_WeaponMod2":
      case t"AttachmentSlots.Smart_Shotgun_WeaponMod1":
      case t"AttachmentSlots.Tech_Shotgun_WeaponMod2":
      case t"AttachmentSlots.Tech_Shotgun_WeaponMod1":
      case t"AttachmentSlots.Power_Shotgun_WeaponMod2_Collectible":
      case t"AttachmentSlots.Power_Shotgun_WeaponMod1_Collectible":
      case t"AttachmentSlots.Power_Shotgun_WeaponMod2":
      case t"AttachmentSlots.Power_Shotgun_WeaponMod1":
      case t"AttachmentSlots.Smart_Handgun_WeaponMod2_Collectible":
      case t"AttachmentSlots.Smart_Handgun_WeaponMod1_Collectible":
      case t"AttachmentSlots.Smart_Handgun_WeaponMod2":
      case t"AttachmentSlots.Smart_Handgun_WeaponMod1":
      case t"AttachmentSlots.Tech_Handgun_WeaponMod2":
      case t"AttachmentSlots.Tech_Handgun_WeaponMod1":
      case t"AttachmentSlots.Power_Handgun_WeaponMod2_Collectible":
      case t"AttachmentSlots.Power_Handgun_WeaponMod1_Collectible":
      case t"AttachmentSlots.Power_Handgun_WeaponMod2":
      case t"AttachmentSlots.Power_Handgun_WeaponMod1":
      case t"AttachmentSlots.Power_Handgun_WeaponMod6":
      case t"AttachmentSlots.Power_Handgun_WeaponMod5":
      case t"AttachmentSlots.Power_Handgun_WeaponMod4":
      case t"AttachmentSlots.Power_Handgun_WeaponMod3":
      case t"AttachmentSlots.Smart_Handgun_WeaponMod6":
      case t"AttachmentSlots.Smart_Handgun_WeaponMod5":
      case t"AttachmentSlots.Smart_Handgun_WeaponMod4":
      case t"AttachmentSlots.Smart_Handgun_WeaponMod3":
      case t"AttachmentSlots.Tech_Handgun_WeaponMod6":
      case t"AttachmentSlots.Tech_Handgun_WeaponMod5":
      case t"AttachmentSlots.Tech_Handgun_WeaponMod4":
      case t"AttachmentSlots.Tech_Handgun_WeaponMod3":
      case t"AttachmentSlots.Smart_AR_SMG_LMG_WeaponMod2":
      case t"AttachmentSlots.Smart_AR_SMG_LMG_WeaponMod1":
      case t"AttachmentSlots.Tech_AR_SMG_LMG_WeaponMod2":
      case t"AttachmentSlots.Tech_AR_SMG_LMG_WeaponMod1":
      case t"AttachmentSlots.Power_AR_SMG_LMG_WeaponMod2_Collectible":
      case t"AttachmentSlots.Power_AR_SMG_LMG_WeaponMod1_Collectible":
      case t"AttachmentSlots.Power_AR_SMG_LMG_WeaponMod2":
      case t"AttachmentSlots.Power_AR_SMG_LMG_WeaponMod1":
        return n"UIIcon.LootingShadow_Mod";
      case t"AttachmentSlots.NanoWiresQuickhackSlot":
      case t"AttachmentSlots.NanoWiresQuickhackSlot1":
      case t"AttachmentSlots.CyberdeckProgram16":
      case t"AttachmentSlots.CyberdeckProgram15":
      case t"AttachmentSlots.CyberdeckProgram14":
      case t"AttachmentSlots.CyberdeckProgram13":
      case t"AttachmentSlots.CyberdeckProgram12":
      case t"AttachmentSlots.CyberdeckProgram11":
      case t"AttachmentSlots.CyberdeckProgram10":
      case t"AttachmentSlots.CyberdeckProgram9":
      case t"AttachmentSlots.CyberdeckProgram8":
      case t"AttachmentSlots.CyberdeckProgram7":
      case t"AttachmentSlots.CyberdeckProgram6":
      case t"AttachmentSlots.CyberdeckProgram5":
      case t"AttachmentSlots.CyberdeckProgram4":
      case t"AttachmentSlots.CyberdeckProgram3":
      case t"AttachmentSlots.CyberdeckProgram2":
      case t"AttachmentSlots.CyberdeckProgram1":
        return n"UIIcon.LootingShadow_Program";
      case t"AttachmentSlots.ArmsCyberwareGeneralSlot":
      case t"AttachmentSlots.ProjectileLauncherWiring":
      case t"AttachmentSlots.ProjectileLauncherRound":
      case t"AttachmentSlots.NanoWiresBattery":
      case t"AttachmentSlots.NanoWiresCable":
      case t"AttachmentSlots.MantisBladesRotor":
      case t"AttachmentSlots.MantisBladesEdge":
      case t"AttachmentSlots.StrongArmsBattery":
      case t"AttachmentSlots.StrongArmsKnuckles":
      case t"AttachmentSlots.KiroshiOpticsSlot3":
      case t"AttachmentSlots.KiroshiOpticsSlot2":
      case t"AttachmentSlots.KiroshiOpticsSlot1":
      case t"AttachmentSlots.BerserkSlot3":
      case t"AttachmentSlots.BerserkSlot2":
      case t"AttachmentSlots.BerserkSlot1":
      case t"AttachmentSlots.SandevistanSlot3":
      case t"AttachmentSlots.SandevistanSlot2":
      case t"AttachmentSlots.SandevistanSlot1":
        return n"UIIcon.LootingShadow_Fragment";
      case t"AttachmentSlots.FootFabricEnhancer3":
      case t"AttachmentSlots.FootFabricEnhancer2":
      case t"AttachmentSlots.FootFabricEnhancer1":
      case t"AttachmentSlots.LegsFabricEnhancer3":
      case t"AttachmentSlots.LegsFabricEnhancer2":
      case t"AttachmentSlots.LegsFabricEnhancer1":
      case t"AttachmentSlots.OuterChestFabricEnhancer3":
      case t"AttachmentSlots.OuterChestFabricEnhancer2":
      case t"AttachmentSlots.OuterChestFabricEnhancer1":
      case t"AttachmentSlots.InnerChestFabricEnhancer3":
      case t"AttachmentSlots.InnerChestFabricEnhancer2":
      case t"AttachmentSlots.InnerChestFabricEnhancer1":
      case t"AttachmentSlots.FaceFabricEnhancer3":
      case t"AttachmentSlots.FaceFabricEnhancer2":
      case t"AttachmentSlots.FaceFabricEnhancer1":
      case t"AttachmentSlots.HeadFabricEnhancer3":
      case t"AttachmentSlots.HeadFabricEnhancer2":
      case t"AttachmentSlots.HeadFabricEnhancer1":
        return n"UIIcon.LootingShadow_Material";
    };
    return UIItemsHelper.GetLootingShadowIcon(itemType, equipmentArea);
  }


@replaceMethod(UIItemsHelper)
  public final static func GetSlotName(slotID: TweakDBID, itemType: gamedataItemType, equipmentArea: gamedataEquipmentArea) -> String {
    switch slotID {
      case t"AttachmentSlots.Scope":
        return "Gameplay-Items-Item Type-Prt_Scope";
      case t"AttachmentSlots.PowerModule":
        return "Gameplay-Items-Item Type-Prt_Muzzle";
      case t"AttachmentSlots.Magazine":
        return "Gameplay-Items-Item Type-Prt_Magazine";
      case t"AttachmentSlots.Throwable_WeaponMod2_Collectible":
      case t"AttachmentSlots.Throwable_WeaponMod1_Collectible":
      case t"AttachmentSlots.Throwable_WeaponMod6":
      case t"AttachmentSlots.Throwable_WeaponMod5":
      case t"AttachmentSlots.Throwable_WeaponMod4":
      case t"AttachmentSlots.Throwable_WeaponMod3":
      case t"AttachmentSlots.Throwable_WeaponMod2":
      case t"AttachmentSlots.Throwable_WeaponMod1":
      case t"AttachmentSlots.Blunt_WeaponMod2_Collectible":
      case t"AttachmentSlots.Blunt_WeaponMod1_Collectible":
      case t"AttachmentSlots.Blunt_WeaponMod6":
      case t"AttachmentSlots.Blunt_WeaponMod5":
      case t"AttachmentSlots.Blunt_WeaponMod4":
      case t"AttachmentSlots.Blunt_WeaponMod3":
      case t"AttachmentSlots.Blunt_WeaponMod2":
      case t"AttachmentSlots.Blunt_WeaponMod1":
      case t"AttachmentSlots.Blade_WeaponMod2_Collectible":
      case t"AttachmentSlots.Blade_WeaponMod1_Collectible":
      case t"AttachmentSlots.Blade_WeaponMod6":
      case t"AttachmentSlots.Blade_WeaponMod5":
      case t"AttachmentSlots.Blade_WeaponMod4":
      case t"AttachmentSlots.Blade_WeaponMod3":
      case t"AttachmentSlots.Blade_WeaponMod2":
      case t"AttachmentSlots.Blade_WeaponMod1":
      case t"AttachmentSlots.Smart_Precision_Sniper_Rifle_WeaponMod2_Collectible":
      case t"AttachmentSlots.Smart_Precision_Sniper_Rifle_WeaponMod1_Collectible":
      case t"AttachmentSlots.Smart_Precision_Sniper_Rifle_WeaponMod2":
      case t"AttachmentSlots.Smart_Precision_Sniper_Rifle_WeaponMod1":
      case t"AttachmentSlots.Tech_Precision_Sniper_Rifle_WeaponMod2_Collectible":
      case t"AttachmentSlots.Tech_Precision_Sniper_Rifle_WeaponMod1_Collectible":
      case t"AttachmentSlots.Tech_Precision_Sniper_Rifle_WeaponMod2":
      case t"AttachmentSlots.Tech_Precision_Sniper_Rifle_WeaponMod1":
      case t"AttachmentSlots.Power_Precision_Sniper_Rifle_WeaponMod2":
      case t"AttachmentSlots.Power_Precision_Sniper_Rifle_WeaponMod1":
      case t"AttachmentSlots.Smart_Precision_Sniper_Rifle_WeaponMod6":
      case t"AttachmentSlots.Smart_Precision_Sniper_Rifle_WeaponMod5":
      case t"AttachmentSlots.Smart_Precision_Sniper_Rifle_WeaponMod4":
      case t"AttachmentSlots.Smart_Precision_Sniper_Rifle_WeaponMod3":
      case t"AttachmentSlots.Tech_Precision_Sniper_Rifle_WeaponMod6":
      case t"AttachmentSlots.Tech_Precision_Sniper_Rifle_WeaponMod5":
      case t"AttachmentSlots.Tech_Precision_Sniper_Rifle_WeaponMod4":
      case t"AttachmentSlots.Tech_Precision_Sniper_Rifle_WeaponMod3":
      case t"AttachmentSlots.Power_Precision_Sniper_Rifle_WeaponMod6":
      case t"AttachmentSlots.Power_Precision_Sniper_Rifle_WeaponMod5":
      case t"AttachmentSlots.Power_Precision_Sniper_Rifle_WeaponMod4":
      case t"AttachmentSlots.Power_Precision_Sniper_Rifle_WeaponMod3":
      case t"AttachmentSlots.Smart_Shotgun_WeaponMod6":
      case t"AttachmentSlots.Smart_Shotgun_WeaponMod5":
      case t"AttachmentSlots.Smart_Shotgun_WeaponMod4":
      case t"AttachmentSlots.Smart_Shotgun_WeaponMod3":
      case t"AttachmentSlots.Tech_Shotgun_WeaponMod6":
      case t"AttachmentSlots.Tech_Shotgun_WeaponMod5":
      case t"AttachmentSlots.Tech_Shotgun_WeaponMod4":
      case t"AttachmentSlots.Tech_Shotgun_WeaponMod3":
      case t"AttachmentSlots.Power_Shotgun_WeaponMod6":
      case t"AttachmentSlots.Power_Shotgun_WeaponMod5":
      case t"AttachmentSlots.Power_Shotgun_WeaponMod4":
      case t"AttachmentSlots.Power_Shotgun_WeaponMod3":
      case t"AttachmentSlots.Smart_AR_SMG_LMG_WeaponMod6":
      case t"AttachmentSlots.Smart_AR_SMG_LMG_WeaponMod5":
      case t"AttachmentSlots.Smart_AR_SMG_LMG_WeaponMod4":
      case t"AttachmentSlots.Smart_AR_SMG_LMG_WeaponMod3":
      case t"AttachmentSlots.Tech_AR_SMG_LMG_WeaponMod6":
      case t"AttachmentSlots.Tech_AR_SMG_LMG_WeaponMod5":
      case t"AttachmentSlots.Tech_AR_SMG_LMG_WeaponMod4":
      case t"AttachmentSlots.Tech_AR_SMG_LMG_WeaponMod3":
      case t"AttachmentSlots.Power_AR_SMG_LMG_WeaponMod6":
      case t"AttachmentSlots.Power_AR_SMG_LMG_WeaponMod5":
      case t"AttachmentSlots.Power_AR_SMG_LMG_WeaponMod4":
      case t"AttachmentSlots.Power_AR_SMG_LMG_WeaponMod3":
      case t"AttachmentSlots.Smart_Shotgun_WeaponMod2":
      case t"AttachmentSlots.Smart_Shotgun_WeaponMod1":
      case t"AttachmentSlots.Tech_Shotgun_WeaponMod2":
      case t"AttachmentSlots.Tech_Shotgun_WeaponMod1":
      case t"AttachmentSlots.Power_Shotgun_WeaponMod2_Collectible":
      case t"AttachmentSlots.Power_Shotgun_WeaponMod1_Collectible":
      case t"AttachmentSlots.Power_Shotgun_WeaponMod2":
      case t"AttachmentSlots.Power_Shotgun_WeaponMod1":
      case t"AttachmentSlots.Smart_Handgun_WeaponMod2_Collectible":
      case t"AttachmentSlots.Smart_Handgun_WeaponMod1_Collectible":
      case t"AttachmentSlots.Smart_Handgun_WeaponMod2":
      case t"AttachmentSlots.Smart_Handgun_WeaponMod1":
      case t"AttachmentSlots.Tech_Handgun_WeaponMod2":
      case t"AttachmentSlots.Tech_Handgun_WeaponMod1":
      case t"AttachmentSlots.Power_Handgun_WeaponMod2_Collectible":
      case t"AttachmentSlots.Power_Handgun_WeaponMod1_Collectible":
      case t"AttachmentSlots.Power_Handgun_WeaponMod2":
      case t"AttachmentSlots.Power_Handgun_WeaponMod1":
      case t"AttachmentSlots.Power_Handgun_WeaponMod6":
      case t"AttachmentSlots.Power_Handgun_WeaponMod5":
      case t"AttachmentSlots.Power_Handgun_WeaponMod4":
      case t"AttachmentSlots.Power_Handgun_WeaponMod3":
      case t"AttachmentSlots.Smart_Handgun_WeaponMod6":
      case t"AttachmentSlots.Smart_Handgun_WeaponMod5":
      case t"AttachmentSlots.Smart_Handgun_WeaponMod4":
      case t"AttachmentSlots.Smart_Handgun_WeaponMod3":
      case t"AttachmentSlots.Tech_Handgun_WeaponMod6":
      case t"AttachmentSlots.Tech_Handgun_WeaponMod5":
      case t"AttachmentSlots.Tech_Handgun_WeaponMod4":
      case t"AttachmentSlots.Tech_Handgun_WeaponMod3":
      case t"AttachmentSlots.Smart_AR_SMG_LMG_WeaponMod2":
      case t"AttachmentSlots.Smart_AR_SMG_LMG_WeaponMod1":
      case t"AttachmentSlots.Tech_AR_SMG_LMG_WeaponMod2":
      case t"AttachmentSlots.Tech_AR_SMG_LMG_WeaponMod1":
      case t"AttachmentSlots.Power_AR_SMG_LMG_WeaponMod2_Collectible":
      case t"AttachmentSlots.Power_AR_SMG_LMG_WeaponMod1_Collectible":
      case t"AttachmentSlots.Power_AR_SMG_LMG_WeaponMod2":
      case t"AttachmentSlots.Power_AR_SMG_LMG_WeaponMod1":
        return "Gameplay-Items-Item Type-Prt_Mod";
      case t"AttachmentSlots.NanoWiresQuickhackSlot":
      case t"AttachmentSlots.NanoWiresQuickhackSlot1":
      case t"AttachmentSlots.CyberdeckProgram16":
      case t"AttachmentSlots.CyberdeckProgram15":
      case t"AttachmentSlots.CyberdeckProgram14":
      case t"AttachmentSlots.CyberdeckProgram13":
      case t"AttachmentSlots.CyberdeckProgram12":
      case t"AttachmentSlots.CyberdeckProgram11":
      case t"AttachmentSlots.CyberdeckProgram10":
      case t"AttachmentSlots.CyberdeckProgram9":
      case t"AttachmentSlots.CyberdeckProgram8":
      case t"AttachmentSlots.CyberdeckProgram7":
      case t"AttachmentSlots.CyberdeckProgram6":
      case t"AttachmentSlots.CyberdeckProgram5":
      case t"AttachmentSlots.CyberdeckProgram4":
      case t"AttachmentSlots.CyberdeckProgram3":
      case t"AttachmentSlots.CyberdeckProgram2":
      case t"AttachmentSlots.CyberdeckProgram1":
        return "Gameplay-Items-Item Type-Prt_Program";
      case t"AttachmentSlots.ArmsCyberwareGeneralSlot":
      case t"AttachmentSlots.ProjectileLauncherWiring":
      case t"AttachmentSlots.ProjectileLauncherRound":
      case t"AttachmentSlots.NanoWiresBattery":
      case t"AttachmentSlots.NanoWiresCable":
      case t"AttachmentSlots.MantisBladesRotor":
      case t"AttachmentSlots.MantisBladesEdge":
      case t"AttachmentSlots.StrongArmsBattery":
      case t"AttachmentSlots.StrongArmsKnuckles":
      case t"AttachmentSlots.KiroshiOpticsSlot3":
      case t"AttachmentSlots.KiroshiOpticsSlot2":
      case t"AttachmentSlots.KiroshiOpticsSlot1":
      case t"AttachmentSlots.BerserkSlot3":
      case t"AttachmentSlots.BerserkSlot2":
      case t"AttachmentSlots.BerserkSlot1":
      case t"AttachmentSlots.SandevistanSlot3":
      case t"AttachmentSlots.SandevistanSlot2":
      case t"AttachmentSlots.SandevistanSlot1":
        return "Gameplay-Items-Item Type-Prt_Fragment";
      case t"AttachmentSlots.FootFabricEnhancer3":
      case t"AttachmentSlots.FootFabricEnhancer2":
      case t"AttachmentSlots.FootFabricEnhancer1":
      case t"AttachmentSlots.LegsFabricEnhancer3":
      case t"AttachmentSlots.LegsFabricEnhancer2":
      case t"AttachmentSlots.LegsFabricEnhancer1":
      case t"AttachmentSlots.OuterChestFabricEnhancer3":
      case t"AttachmentSlots.OuterChestFabricEnhancer2":
      case t"AttachmentSlots.OuterChestFabricEnhancer1":
      case t"AttachmentSlots.InnerChestFabricEnhancer3":
      case t"AttachmentSlots.InnerChestFabricEnhancer2":
      case t"AttachmentSlots.InnerChestFabricEnhancer1":
      case t"AttachmentSlots.FaceFabricEnhancer3":
      case t"AttachmentSlots.FaceFabricEnhancer2":
      case t"AttachmentSlots.FaceFabricEnhancer1":
      case t"AttachmentSlots.HeadFabricEnhancer3":
      case t"AttachmentSlots.HeadFabricEnhancer2":
      case t"AttachmentSlots.HeadFabricEnhancer1":
        return "Gameplay-Items-Item Type-Prt_FabricEnhancer";
    };
    return UIItemsHelper.GetSlotName(itemType, equipmentArea);
  }


@replaceMethod(UIItemsHelper)
  public final static func GetEmptySlotName(slotId: TweakDBID) -> String {
    switch slotId {
      case t"AttachmentSlots.Smart_Precision_Sniper_Rifle_WeaponMod2_Collectible":
      case t"AttachmentSlots.Smart_Precision_Sniper_Rifle_WeaponMod1_Collectible":
      case t"AttachmentSlots.Smart_Precision_Sniper_Rifle_WeaponMod2":
      case t"AttachmentSlots.Smart_Precision_Sniper_Rifle_WeaponMod1":
      case t"AttachmentSlots.Tech_Precision_Sniper_Rifle_WeaponMod2_Collectible":
      case t"AttachmentSlots.Tech_Precision_Sniper_Rifle_WeaponMod1_Collectible":
      case t"AttachmentSlots.Tech_Precision_Sniper_Rifle_WeaponMod2":
      case t"AttachmentSlots.Tech_Precision_Sniper_Rifle_WeaponMod1":
      case t"AttachmentSlots.Power_Precision_Sniper_Rifle_WeaponMod2":
      case t"AttachmentSlots.Power_Precision_Sniper_Rifle_WeaponMod1":
      case t"AttachmentSlots.Smart_Precision_Sniper_Rifle_WeaponMod6":
      case t"AttachmentSlots.Smart_Precision_Sniper_Rifle_WeaponMod5":
      case t"AttachmentSlots.Smart_Precision_Sniper_Rifle_WeaponMod4":
      case t"AttachmentSlots.Smart_Precision_Sniper_Rifle_WeaponMod3":
      case t"AttachmentSlots.Tech_Precision_Sniper_Rifle_WeaponMod6":
      case t"AttachmentSlots.Tech_Precision_Sniper_Rifle_WeaponMod5":
      case t"AttachmentSlots.Tech_Precision_Sniper_Rifle_WeaponMod4":
      case t"AttachmentSlots.Tech_Precision_Sniper_Rifle_WeaponMod3":
      case t"AttachmentSlots.Power_Precision_Sniper_Rifle_WeaponMod6":
      case t"AttachmentSlots.Power_Precision_Sniper_Rifle_WeaponMod5":
      case t"AttachmentSlots.Power_Precision_Sniper_Rifle_WeaponMod4":
      case t"AttachmentSlots.Power_Precision_Sniper_Rifle_WeaponMod3":
      case t"AttachmentSlots.Smart_Shotgun_WeaponMod6":
      case t"AttachmentSlots.Smart_Shotgun_WeaponMod5":
      case t"AttachmentSlots.Smart_Shotgun_WeaponMod4":
      case t"AttachmentSlots.Smart_Shotgun_WeaponMod3":
      case t"AttachmentSlots.Tech_Shotgun_WeaponMod6":
      case t"AttachmentSlots.Tech_Shotgun_WeaponMod5":
      case t"AttachmentSlots.Tech_Shotgun_WeaponMod4":
      case t"AttachmentSlots.Tech_Shotgun_WeaponMod3":
      case t"AttachmentSlots.Power_Shotgun_WeaponMod6":
      case t"AttachmentSlots.Power_Shotgun_WeaponMod5":
      case t"AttachmentSlots.Power_Shotgun_WeaponMod4":
      case t"AttachmentSlots.Power_Shotgun_WeaponMod3":
      case t"AttachmentSlots.Smart_AR_SMG_LMG_WeaponMod6":
      case t"AttachmentSlots.Smart_AR_SMG_LMG_WeaponMod5":
      case t"AttachmentSlots.Smart_AR_SMG_LMG_WeaponMod4":
      case t"AttachmentSlots.Smart_AR_SMG_LMG_WeaponMod3":
      case t"AttachmentSlots.Tech_AR_SMG_LMG_WeaponMod6":
      case t"AttachmentSlots.Tech_AR_SMG_LMG_WeaponMod5":
      case t"AttachmentSlots.Tech_AR_SMG_LMG_WeaponMod4":
      case t"AttachmentSlots.Tech_AR_SMG_LMG_WeaponMod3":
      case t"AttachmentSlots.Power_AR_SMG_LMG_WeaponMod6":
      case t"AttachmentSlots.Power_AR_SMG_LMG_WeaponMod5":
      case t"AttachmentSlots.Power_AR_SMG_LMG_WeaponMod4":
      case t"AttachmentSlots.Power_AR_SMG_LMG_WeaponMod3":
      case t"AttachmentSlots.Smart_Shotgun_WeaponMod2":
      case t"AttachmentSlots.Smart_Shotgun_WeaponMod1":
      case t"AttachmentSlots.Tech_Shotgun_WeaponMod2":
      case t"AttachmentSlots.Tech_Shotgun_WeaponMod1":
      case t"AttachmentSlots.Power_Shotgun_WeaponMod2_Collectible":
      case t"AttachmentSlots.Power_Shotgun_WeaponMod1_Collectible":
      case t"AttachmentSlots.Power_Shotgun_WeaponMod2":
      case t"AttachmentSlots.Power_Shotgun_WeaponMod1":
      case t"AttachmentSlots.Smart_Handgun_WeaponMod2_Collectible":
      case t"AttachmentSlots.Smart_Handgun_WeaponMod1_Collectible":
      case t"AttachmentSlots.Smart_Handgun_WeaponMod2":
      case t"AttachmentSlots.Smart_Handgun_WeaponMod1":
      case t"AttachmentSlots.Tech_Handgun_WeaponMod2":
      case t"AttachmentSlots.Tech_Handgun_WeaponMod1":
      case t"AttachmentSlots.Power_Handgun_WeaponMod2_Collectible":
      case t"AttachmentSlots.Power_Handgun_WeaponMod1_Collectible":
      case t"AttachmentSlots.Power_Handgun_WeaponMod2":
      case t"AttachmentSlots.Power_Handgun_WeaponMod1":
      case t"AttachmentSlots.Power_Handgun_WeaponMod6":
      case t"AttachmentSlots.Power_Handgun_WeaponMod5":
      case t"AttachmentSlots.Power_Handgun_WeaponMod4":
      case t"AttachmentSlots.Power_Handgun_WeaponMod3":
      case t"AttachmentSlots.Smart_Handgun_WeaponMod6":
      case t"AttachmentSlots.Smart_Handgun_WeaponMod5":
      case t"AttachmentSlots.Smart_Handgun_WeaponMod4":
      case t"AttachmentSlots.Smart_Handgun_WeaponMod3":
      case t"AttachmentSlots.Tech_Handgun_WeaponMod6":
      case t"AttachmentSlots.Tech_Handgun_WeaponMod5":
      case t"AttachmentSlots.Tech_Handgun_WeaponMod4":
      case t"AttachmentSlots.Tech_Handgun_WeaponMod3":
      case t"AttachmentSlots.Smart_AR_SMG_LMG_WeaponMod2":
      case t"AttachmentSlots.Smart_AR_SMG_LMG_WeaponMod1":
      case t"AttachmentSlots.Tech_AR_SMG_LMG_WeaponMod2":
      case t"AttachmentSlots.Tech_AR_SMG_LMG_WeaponMod1":
      case t"AttachmentSlots.Power_AR_SMG_LMG_WeaponMod2_Collectible":
      case t"AttachmentSlots.Power_AR_SMG_LMG_WeaponMod1_Collectible":
      case t"AttachmentSlots.Power_AR_SMG_LMG_WeaponMod2":
      case t"AttachmentSlots.Power_AR_SMG_LMG_WeaponMod1":
        return "UI-Labels-EmptyModSlot";
      case t"AttachmentSlots.Throwable_WeaponMod2_Collectible":
      case t"AttachmentSlots.Throwable_WeaponMod1_Collectible":
      case t"AttachmentSlots.Throwable_WeaponMod6":
      case t"AttachmentSlots.Throwable_WeaponMod5":
      case t"AttachmentSlots.Throwable_WeaponMod4":
      case t"AttachmentSlots.Throwable_WeaponMod3":
      case t"AttachmentSlots.Throwable_WeaponMod2":
      case t"AttachmentSlots.Throwable_WeaponMod1":
      case t"AttachmentSlots.Blunt_WeaponMod2_Collectible":
      case t"AttachmentSlots.Blunt_WeaponMod1_Collectible":
      case t"AttachmentSlots.Blunt_WeaponMod6":
      case t"AttachmentSlots.Blunt_WeaponMod5":
      case t"AttachmentSlots.Blunt_WeaponMod4":
      case t"AttachmentSlots.Blunt_WeaponMod3":
      case t"AttachmentSlots.Blunt_WeaponMod2":
      case t"AttachmentSlots.Blunt_WeaponMod1":
      case t"AttachmentSlots.Blade_WeaponMod2_Collectible":
      case t"AttachmentSlots.Blade_WeaponMod1_Collectible":
      case t"AttachmentSlots.Blade_WeaponMod6":
      case t"AttachmentSlots.Blade_WeaponMod5":
      case t"AttachmentSlots.Blade_WeaponMod4":
      case t"AttachmentSlots.Blade_WeaponMod3":
      case t"AttachmentSlots.Blade_WeaponMod2":
      case t"AttachmentSlots.Blade_WeaponMod1":
        return "UI-Labels-EmptyMeleeModSlot";
      case t"AttachmentSlots.Scope":
        return "UI-Labels-EmptyScopeSlot";
      case t"AttachmentSlots.PowerModule":
        return "UI-Labels-EmptyMuzzleSlot";
      case t"AttachmentSlots.FootFabricEnhancer3":
      case t"AttachmentSlots.FootFabricEnhancer2":
      case t"AttachmentSlots.FootFabricEnhancer1":
      case t"AttachmentSlots.LegsFabricEnhancer3":
      case t"AttachmentSlots.LegsFabricEnhancer2":
      case t"AttachmentSlots.LegsFabricEnhancer1":
      case t"AttachmentSlots.OuterChestFabricEnhancer4":
      case t"AttachmentSlots.OuterChestFabricEnhancer3":
      case t"AttachmentSlots.OuterChestFabricEnhancer2":
      case t"AttachmentSlots.OuterChestFabricEnhancer1":
      case t"AttachmentSlots.InnerChestFabricEnhancer4":
      case t"AttachmentSlots.InnerChestFabricEnhancer3":
      case t"AttachmentSlots.InnerChestFabricEnhancer2":
      case t"AttachmentSlots.InnerChestFabricEnhancer1":
      case t"AttachmentSlots.FaceFabricEnhancer3":
      case t"AttachmentSlots.FaceFabricEnhancer2":
      case t"AttachmentSlots.FaceFabricEnhancer1":
      case t"AttachmentSlots.HeadFabricEnhancer3":
      case t"AttachmentSlots.HeadFabricEnhancer2":
      case t"AttachmentSlots.HeadFabricEnhancer1":
        return "UI-Labels-EmptyClothingModSlot";
      case t"AttachmentSlots.NanoWiresQuickhackSlot":
      case t"AttachmentSlots.NanoWiresQuickhackSlot1":
      case t"AttachmentSlots.CyberdeckProgram16":
      case t"AttachmentSlots.CyberdeckProgram15":
      case t"AttachmentSlots.CyberdeckProgram14":
      case t"AttachmentSlots.CyberdeckProgram13":
      case t"AttachmentSlots.CyberdeckProgram12":
      case t"AttachmentSlots.CyberdeckProgram11":
      case t"AttachmentSlots.CyberdeckProgram10":
      case t"AttachmentSlots.CyberdeckProgram9":
      case t"AttachmentSlots.CyberdeckProgram8":
      case t"AttachmentSlots.CyberdeckProgram7":
      case t"AttachmentSlots.CyberdeckProgram6":
      case t"AttachmentSlots.CyberdeckProgram5":
      case t"AttachmentSlots.CyberdeckProgram4":
      case t"AttachmentSlots.CyberdeckProgram3":
      case t"AttachmentSlots.CyberdeckProgram2":
      case t"AttachmentSlots.CyberdeckProgram1":
        return "UI-Labels-EmptyProgramSlot";
      case t"AttachmentSlots.KiroshiOpticsSlot3":
      case t"AttachmentSlots.KiroshiOpticsSlot2":
      case t"AttachmentSlots.KiroshiOpticsSlot1":
      case t"AttachmentSlots.KERSSlot3":
      case t"AttachmentSlots.KERSSlot2":
      case t"AttachmentSlots.KERSSlot1":
      case t"AttachmentSlots.BerserkSlot3":
      case t"AttachmentSlots.BerserkSlot2":
      case t"AttachmentSlots.BerserkSlot1":
      case t"AttachmentSlots.SandevistanSlot3":
      case t"AttachmentSlots.SandevistanSlot2":
      case t"AttachmentSlots.SandevistanSlot1":
        return "UI-Labels-EmptyCyberwareModSlot";
    };
    return "UI-Labels-EmptySlot";
  }