import class inkScrollController extends inkLogicController
{
	public import function Scroll( value : Float, isMouseWheel : Bool );
	public import function SetScrollPosition( newValue : Float );
	public import function UpdateScrollPositionFromScrollArea();
	public import function SetInputDisabled( disabled : Bool );
	public import function EnsureVisible( widget : weak< inkWidget > );
}

import enum inkEScrollDirection
{
	Vertical,
	Horizontal,
}

