class RegisterDelamainTaxiRequest extends ScriptableSystemRequest
{
	var delamainTaxi : weak< DelamainTaxiComponent >;
}

class DelamainTaxiArrivedRequest extends ScriptableSystemRequest
{
}

class StartDelamainTaxiRequest extends ScriptableSystemRequest
{
	var m_price : Int32;
}

class CancelDelamainRideRequest extends ScriptableSystemRequest
{
	var forceExit : Bool;
}

class SetTravelDestinationRequest extends ScriptableSystemRequest
{
	var mappinID : NewMappinID;
	var cost : Int32;
}

class DelamainTaxiCancelledRequest extends ScriptableSystemRequest
{
}

class DelamainTaxiMenuToggledEvent extends ScriptableSystemRequest
{
	var isEnabled : Bool;
}

class UnregisterCurrentTaxiRequest extends ScriptableSystemRequest
{
}

class SetHUDHiddenRequest extends ScriptableSystemRequest
{
	var hidden : Bool;
}

class PayTravelRequest extends ScriptableSystemRequest
{
}

class CancelDriveIfNecessaryRequest extends ScriptableSystemRequest
{
}

class DelamainTaxiSystem extends ScriptableSystem
{
	private var m_isDelamainTaxiEnabledOnMap : Bool;
	private var m_delamainMappinID : NewMappinID;
	private var m_currentTravelCost : Int32;
	private var m_HUDHidden : Bool;
	default m_HUDHidden = false;
	private var m_delamainTaxi : weak< DelamainTaxiComponent >;

	public const function IsDelamainTaxiEnabledOnMap() : Bool
	{
		return m_isDelamainTaxiEnabledOnMap;
	}

	public const function HasActiveDestination() : Bool
	{
		return m_delamainMappinID.value != 0;
	}

	public const function GetTravelCost() : Int32
	{
		return m_currentTravelCost;
	}

	private function OnSetTravelDestinationRequest( request : SetTravelDestinationRequest )
	{
		m_delamainMappinID = request.mappinID;
		m_currentTravelCost = request.cost;
	}

	private function OnRegisterDelamainTaxiRequest( request : RegisterDelamainTaxiRequest )
	{
		m_delamainTaxi = request.delamainTaxi;
	}

	private function OnDelamainTaxiArrivedRequest( request : DelamainTaxiArrivedRequest )
	{
		m_delamainMappinID.value = 0;
		m_delamainTaxi.OnDelamainTaxiArrivedEvent();
	}

	private function OnStartDelamainTaxiRequest( request : StartDelamainTaxiRequest )
	{
		m_delamainTaxi.StartAutoDrive();
		m_currentTravelCost = request.m_price;
	}

	private export function OnCancelDelamainRideRequest( request : CancelDelamainRideRequest )
	{
		m_delamainTaxi.CancelRide( request.forceExit );
	}

	private export function OnDelamainTaxiCancelledRequest( request : DelamainTaxiCancelledRequest )
	{
		GameInstance.GetMappinSystem( GetGameInstance() ).UnregisterMappin( m_delamainMappinID );
		m_delamainMappinID.value = 0;
	}

	private export function OnDelamainTaxiMenuToggledRequest( evt : DelamainTaxiMenuToggledEvent )
	{
		m_isDelamainTaxiEnabledOnMap = evt.isEnabled;
	}

	private export function OnUnregisterCurrentTaxiRequest( evt : UnregisterCurrentTaxiRequest )
	{
		var vehicle : VehicleObject;
		vehicle = ( ( VehicleObject )( m_delamainTaxi.GetOwner() ) );
		GameInstance.GetVehicleSystem( GetGameInstance() ).UnregisterPlayerVehicle( vehicle.GetRecordID() );
		m_delamainTaxi = NULL;
	}

	private export function OnSetHUDHiddenRequest( request : SetHUDHiddenRequest )
	{
		if( m_HUDHidden == request.hidden )
		{
			return;
		}
		m_HUDHidden = request.hidden;
		if( m_HUDHidden )
		{
			GameInstance.GetUISystem( GetGameInstance() ).PushGameContext( UIGameContext.DelamainTaxi );
		}
		else
		{
			GameInstance.GetUISystem( GetGameInstance() ).PopGameContext( UIGameContext.DelamainTaxi );
		}
	}

	private export function OnPayTravelRequest( request : PayTravelRequest )
	{
		var player : GameObject;
		var transactionSystem : TransactionSystem;
		player = GetPlayer( GetGameInstance() );
		transactionSystem = GameInstance.GetTransactionSystem( GetGameInstance() );
		transactionSystem.RemoveItem( player, MarketSystem.Money(), m_currentTravelCost );
	}

	private export function OnCancelDriveIfNecessaryRequest( request : CancelDriveIfNecessaryRequest )
	{
		if( m_delamainTaxi && ( m_delamainMappinID.value != 0 ) )
		{
			m_delamainTaxi.CancelRide( false );
		}
	}

}

