[[UNRESOLVED_REF]]
id = "ARCHIVEXL_12701"
span_starts_with = "ArchiveXL"
message = "Install ArchiveXL 1.27.1 or higher"

[[UNRESOLVED_METHOD]]
id = "ARCHIVEXL_12701"
span_starts_with = "ArchiveXL"
message = "Install ArchiveXL 1.27.1 or higher"

[[UNRESOLVED_REF]]
id = "CODEWARE_12005"
span_starts_with = "Codeware"
message = "Install Codeware 1.20.3 or higher"

[[UNRESOLVED_METHOD]]
id = "CODEWARE_12005"
span_starts_with = "Codeware"
message = "Install Codeware 1.20.3 or higher"
