[[UNRESOLVED_REF]]
id = "LIZZIESBDS_MISSING_TWEAKXL"
file = "LizziesBDs/MenuUIController.reds"
line_contains = "TweakDBManager"
message = "Lizzie's Braindances depends on TweakXL but you don't have it installed. Try to (re)install it and make sure that you have \"red4ext\\plugins\\TweakXL\" folder."

[[UNRESOLVED_IMPORT]]
id = "LIZZIESBDS_MISSING_CODEWARE"
file = "LizziesBDs/MenuUIController.reds"
line_contains = "Codeware"
message = "Lizzie's Braindances depends on Codeware but you don't have it installed. Try to (re)install it and make sure that you have \"red4ext\\plugins\\Codeware\" folder."

[[UNRESOLVED_REF]]
id = "LIZZIESBDS_MISSING_ARCHIVEXL"
file = "LizziesBDs/MenuUIController.reds"
line_contains = "ArchiveXL"
message = "Lizzie's Braindances depends on ArchiveXL but you don't have it installed. Try to (re)install it and make sure that you have \"red4ext\\plugins\\ArchiveXL\" folder."
