[[UNRESOLVED_REF]]
id = "ARCHIVEXL_1211"
span_starts_with = "ArchiveXL"
message = "Install ArchiveXL 1.21.1 or higher"

[[UNRESOLVED_REF]]
id = "TWEAKXL_1109"
span_starts_with = "TweakXL"
message = "Install TweakXL 1.10.9 or higher"

[[UNRESOLVED_REF]]
id = "CODEWARE_1150"
span_starts_with = "Codeware"
message = "Install Codeware 1.15.0 or higher"